// Code generated by Fern. DO NOT EDIT.

package client

import (
	http "net/http"
	agents "sdk/agents"
	contacts "sdk/contacts"
	core "sdk/core"
	customers "sdk/customers"
	internal "sdk/internal"
	option "sdk/option"
	ordersclient "sdk/orders/client"
	traces "sdk/traces"
	usage "sdk/usage"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Customers *customers.Client
	Agents    *agents.Client
	Contacts  *contacts.Client
	Orders    *ordersclient.Client
	Usage     *usage.Client
	Traces    *traces.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:    options.ToHeader(),
		Customers: customers.NewClient(opts...),
		Agents:    agents.NewClient(opts...),
		Contacts:  contacts.NewClient(opts...),
		Orders:    ordersclient.NewClient(opts...),
		Usage:     usage.NewClient(opts...),
		Traces:    traces.NewClient(opts...),
	}
}
