// Code generated by Fern. DO NOT EDIT.

package client

import (
	checkouts "github.com/paid-ai/paid-go/checkouts"
	contacts "github.com/paid-ai/paid-go/contacts"
	core "github.com/paid-ai/paid-go/core"
	credits "github.com/paid-ai/paid-go/credits"
	customerportals "github.com/paid-ai/paid-go/customerportals"
	customers "github.com/paid-ai/paid-go/customers"
	internal "github.com/paid-ai/paid-go/internal"
	invoices "github.com/paid-ai/paid-go/invoices"
	option "github.com/paid-ai/paid-go/option"
	orders "github.com/paid-ai/paid-go/orders"
	products "github.com/paid-ai/paid-go/products"
	signals "github.com/paid-ai/paid-go/signals"
	valuereceipts "github.com/paid-ai/paid-go/valuereceipts"
	webhooks "github.com/paid-ai/paid-go/webhooks"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Products        *products.Client
	Customers       *customers.Client
	Contacts        *contacts.Client
	Orders          *orders.Client
	Invoices        *invoices.Client
	Signals         *signals.Client
	Credits         *credits.Client
	Checkouts       *checkouts.Client
	CustomerPortals *customerportals.Client
	ValueReceipts   *valuereceipts.Client
	Webhooks        *webhooks.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:          options.ToHeader(),
		Products:        products.NewClient(opts...),
		Customers:       customers.NewClient(opts...),
		Contacts:        contacts.NewClient(opts...),
		Orders:          orders.NewClient(opts...),
		Invoices:        invoices.NewClient(opts...),
		Signals:         signals.NewClient(opts...),
		Credits:         credits.NewClient(opts...),
		Checkouts:       checkouts.NewClient(opts...),
		CustomerPortals: customerportals.NewClient(opts...),
		ValueReceipts:   valuereceipts.NewClient(opts...),
		Webhooks:        webhooks.NewClient(opts...),
	}
}
