// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/paid-ai/paid-go/internal"
	time "time"
)

type AnalyticsQueryRequest struct {
	// A single ClickHouse SELECT (or WITH ... SELECT) statement against the analytics views. Results are automatically scoped to your organization. See GET /schema for the available views and columns.
	Query string `json:"query" url:"-"`
}

type GetSignalsMetadataRequest struct {
	// Restrict discovery to a single signal name.
	SignalName *string `json:"-" url:"signalName,omitempty"`
	// Start of the discovery window. Defaults to 30 days ago.
	FromDate *time.Time `json:"-" url:"fromDate,omitempty"`
	// End of the discovery window. Defaults to now.
	ToDate *time.Time `json:"-" url:"toDate,omitempty"`
}

type AnalyticsColumn struct {
	Name string `json:"name" url:"name"`
	// ClickHouse column type
	Type string `json:"type" url:"type"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AnalyticsColumn) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AnalyticsColumn) GetType() string {
	if a == nil {
		return ""
	}
	return a.Type
}

func (a *AnalyticsColumn) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AnalyticsColumn) UnmarshalJSON(data []byte) error {
	type unmarshaler AnalyticsColumn
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AnalyticsColumn(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AnalyticsColumn) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AnalyticsQueryResponse struct {
	Columns []*AnalyticsColumn `json:"columns" url:"columns"`
	// Result rows; values are ordered to match `columns`. 64-bit integers (UInt64/Int64 — counts, sums, amounts in cents, ids) are returned as JSON strings to preserve precision; parse them client-side as needed.
	Rows [][]interface{}             `json:"rows" url:"rows"`
	Meta *AnalyticsQueryResponseMeta `json:"meta" url:"meta"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AnalyticsQueryResponse) GetColumns() []*AnalyticsColumn {
	if a == nil {
		return nil
	}
	return a.Columns
}

func (a *AnalyticsQueryResponse) GetRows() [][]interface{} {
	if a == nil {
		return nil
	}
	return a.Rows
}

func (a *AnalyticsQueryResponse) GetMeta() *AnalyticsQueryResponseMeta {
	if a == nil {
		return nil
	}
	return a.Meta
}

func (a *AnalyticsQueryResponse) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AnalyticsQueryResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AnalyticsQueryResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AnalyticsQueryResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AnalyticsQueryResponse) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AnalyticsQueryResponseMeta struct {
	RowCount  int     `json:"rowCount" url:"rowCount"`
	ElapsedMs float64 `json:"elapsedMs" url:"elapsedMs"`
	// True when the result hit the row cap and was truncated. Narrow the query (shorter date range, LIMIT, coarser grouping) to see the rest.
	Truncated bool `json:"truncated" url:"truncated"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AnalyticsQueryResponseMeta) GetRowCount() int {
	if a == nil {
		return 0
	}
	return a.RowCount
}

func (a *AnalyticsQueryResponseMeta) GetElapsedMs() float64 {
	if a == nil {
		return 0
	}
	return a.ElapsedMs
}

func (a *AnalyticsQueryResponseMeta) GetTruncated() bool {
	if a == nil {
		return false
	}
	return a.Truncated
}

func (a *AnalyticsQueryResponseMeta) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AnalyticsQueryResponseMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler AnalyticsQueryResponseMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AnalyticsQueryResponseMeta(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AnalyticsQueryResponseMeta) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AnalyticsSchemaColumn struct {
	Name string `json:"name" url:"name"`
	// ClickHouse column type
	Type    string `json:"type" url:"type"`
	Comment string `json:"comment" url:"comment"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AnalyticsSchemaColumn) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AnalyticsSchemaColumn) GetType() string {
	if a == nil {
		return ""
	}
	return a.Type
}

func (a *AnalyticsSchemaColumn) GetComment() string {
	if a == nil {
		return ""
	}
	return a.Comment
}

func (a *AnalyticsSchemaColumn) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AnalyticsSchemaColumn) UnmarshalJSON(data []byte) error {
	type unmarshaler AnalyticsSchemaColumn
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AnalyticsSchemaColumn(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AnalyticsSchemaColumn) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AnalyticsSchemaResponse struct {
	Views []*AnalyticsSchemaView `json:"views" url:"views"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AnalyticsSchemaResponse) GetViews() []*AnalyticsSchemaView {
	if a == nil {
		return nil
	}
	return a.Views
}

func (a *AnalyticsSchemaResponse) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AnalyticsSchemaResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AnalyticsSchemaResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AnalyticsSchemaResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AnalyticsSchemaResponse) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AnalyticsSchemaView struct {
	Name    string                   `json:"name" url:"name"`
	Comment string                   `json:"comment" url:"comment"`
	Columns []*AnalyticsSchemaColumn `json:"columns" url:"columns"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AnalyticsSchemaView) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AnalyticsSchemaView) GetComment() string {
	if a == nil {
		return ""
	}
	return a.Comment
}

func (a *AnalyticsSchemaView) GetColumns() []*AnalyticsSchemaColumn {
	if a == nil {
		return nil
	}
	return a.Columns
}

func (a *AnalyticsSchemaView) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AnalyticsSchemaView) UnmarshalJSON(data []byte) error {
	type unmarshaler AnalyticsSchemaView
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AnalyticsSchemaView(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AnalyticsSchemaView) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type SignalsMetadataResponse struct {
	Signals []*SignalsMetadataResponseSignalsItem `json:"signals" url:"signals"`
	Meta    *SignalsMetadataResponseMeta          `json:"meta" url:"meta"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SignalsMetadataResponse) GetSignals() []*SignalsMetadataResponseSignalsItem {
	if s == nil {
		return nil
	}
	return s.Signals
}

func (s *SignalsMetadataResponse) GetMeta() *SignalsMetadataResponseMeta {
	if s == nil {
		return nil
	}
	return s.Meta
}

func (s *SignalsMetadataResponse) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SignalsMetadataResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SignalsMetadataResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SignalsMetadataResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SignalsMetadataResponse) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SignalsMetadataResponseMeta struct {
	FromDate string `json:"fromDate" url:"fromDate"`
	ToDate   string `json:"toDate" url:"toDate"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SignalsMetadataResponseMeta) GetFromDate() string {
	if s == nil {
		return ""
	}
	return s.FromDate
}

func (s *SignalsMetadataResponseMeta) GetToDate() string {
	if s == nil {
		return ""
	}
	return s.ToDate
}

func (s *SignalsMetadataResponseMeta) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SignalsMetadataResponseMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler SignalsMetadataResponseMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SignalsMetadataResponseMeta(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SignalsMetadataResponseMeta) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SignalsMetadataResponseSignalsItem struct {
	SignalName string                                         `json:"signalName" url:"signalName"`
	Paths      []*SignalsMetadataResponseSignalsItemPathsItem `json:"paths" url:"paths"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SignalsMetadataResponseSignalsItem) GetSignalName() string {
	if s == nil {
		return ""
	}
	return s.SignalName
}

func (s *SignalsMetadataResponseSignalsItem) GetPaths() []*SignalsMetadataResponseSignalsItemPathsItem {
	if s == nil {
		return nil
	}
	return s.Paths
}

func (s *SignalsMetadataResponseSignalsItem) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SignalsMetadataResponseSignalsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler SignalsMetadataResponseSignalsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SignalsMetadataResponseSignalsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SignalsMetadataResponseSignalsItem) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SignalsMetadataResponseSignalsItemPathsItem struct {
	// JSON path inside the signal `data` payload, usable in queries as e.g. `data.<path>::String`.
	Path string `json:"path" url:"path"`
	// ClickHouse dynamic types observed for this path.
	Types []string `json:"types" url:"types"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SignalsMetadataResponseSignalsItemPathsItem) GetPath() string {
	if s == nil {
		return ""
	}
	return s.Path
}

func (s *SignalsMetadataResponseSignalsItemPathsItem) GetTypes() []string {
	if s == nil {
		return nil
	}
	return s.Types
}

func (s *SignalsMetadataResponseSignalsItemPathsItem) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SignalsMetadataResponseSignalsItemPathsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler SignalsMetadataResponseSignalsItemPathsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SignalsMetadataResponseSignalsItemPathsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SignalsMetadataResponseSignalsItemPathsItem) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
