// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/paid-ai/paid-go/internal"
	time "time"
)

type CostIngestRequest struct {
	Costs []*Cost `json:"costs,omitempty" url:"-"`
}

type ProductAttribution struct {
	ProductByID         *ProductByID
	ProductByExternalID *ProductByExternalID

	typ string
}

func (p *ProductAttribution) GetProductByID() *ProductByID {
	if p == nil {
		return nil
	}
	return p.ProductByID
}

func (p *ProductAttribution) GetProductByExternalID() *ProductByExternalID {
	if p == nil {
		return nil
	}
	return p.ProductByExternalID
}

func (p *ProductAttribution) UnmarshalJSON(data []byte) error {
	valueProductByID := new(ProductByID)
	if err := json.Unmarshal(data, &valueProductByID); err == nil {
		p.typ = "ProductByID"
		p.ProductByID = valueProductByID
		return nil
	}
	valueProductByExternalID := new(ProductByExternalID)
	if err := json.Unmarshal(data, &valueProductByExternalID); err == nil {
		p.typ = "ProductByExternalID"
		p.ProductByExternalID = valueProductByExternalID
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, p)
}

func (p ProductAttribution) MarshalJSON() ([]byte, error) {
	if p.typ == "ProductByID" || p.ProductByID != nil {
		return json.Marshal(p.ProductByID)
	}
	if p.typ == "ProductByExternalID" || p.ProductByExternalID != nil {
		return json.Marshal(p.ProductByExternalID)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", p)
}

type ProductAttributionVisitor interface {
	VisitProductByID(*ProductByID) error
	VisitProductByExternalID(*ProductByExternalID) error
}

func (p *ProductAttribution) Accept(visitor ProductAttributionVisitor) error {
	if p.typ == "ProductByID" || p.ProductByID != nil {
		return visitor.VisitProductByID(p.ProductByID)
	}
	if p.typ == "ProductByExternalID" || p.ProductByExternalID != nil {
		return visitor.VisitProductByExternalID(p.ProductByExternalID)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", p)
}

type Cost struct {
	Type  string
	Cost  *PrecomputedCost
	Usage *UsageCost
}

func (c *Cost) GetType() string {
	if c == nil {
		return ""
	}
	return c.Type
}

func (c *Cost) GetCost() *PrecomputedCost {
	if c == nil {
		return nil
	}
	return c.Cost
}

func (c *Cost) GetUsage() *UsageCost {
	if c == nil {
		return nil
	}
	return c.Usage
}

func (c *Cost) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	c.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", c)
	}
	switch unmarshaler.Type {
	case "cost":
		value := new(PrecomputedCost)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		c.Cost = value
	case "usage":
		value := new(UsageCost)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		c.Usage = value
	}
	return nil
}

func (c Cost) MarshalJSON() ([]byte, error) {
	if err := c.validate(); err != nil {
		return nil, err
	}
	if c.Cost != nil {
		return internal.MarshalJSONWithExtraProperty(c.Cost, "type", "cost")
	}
	if c.Usage != nil {
		return internal.MarshalJSONWithExtraProperty(c.Usage, "type", "usage")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", c)
}

type CostVisitor interface {
	VisitCost(*PrecomputedCost) error
	VisitUsage(*UsageCost) error
}

func (c *Cost) Accept(visitor CostVisitor) error {
	if c.Cost != nil {
		return visitor.VisitCost(c.Cost)
	}
	if c.Usage != nil {
		return visitor.VisitUsage(c.Usage)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", c)
}

func (c *Cost) validate() error {
	if c == nil {
		return fmt.Errorf("type %T is nil", c)
	}
	var fields []string
	if c.Cost != nil {
		fields = append(fields, "cost")
	}
	if c.Usage != nil {
		fields = append(fields, "usage")
	}
	if len(fields) == 0 {
		if c.Type != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", c, c.Type)
		}
		return fmt.Errorf("type %T is empty", c)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", c, fields)
	}
	if c.Type != "" {
		field := fields[0]
		if c.Type != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				c,
				c.Type,
				c,
			)
		}
	}
	return nil
}

type CostIngestResponse struct {
	// Number of records persisted.
	Ingested int `json:"ingested" url:"ingested"`
	// Number of records skipped because their `idempotencyKey` matched a previously ingested record.
	Duplicates int `json:"duplicates" url:"duplicates"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CostIngestResponse) GetIngested() int {
	if c == nil {
		return 0
	}
	return c.Ingested
}

func (c *CostIngestResponse) GetDuplicates() int {
	if c == nil {
		return 0
	}
	return c.Duplicates
}

func (c *CostIngestResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CostIngestResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CostIngestResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CostIngestResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CostIngestResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// If supplied, overrides server-side pricing. The usage breakdown is still recorded for analytics.
type CostOverride struct {
	Amount float64 `json:"amount" url:"amount"`
	// ISO 4217 currency code, e.g. "USD".
	Currency string `json:"currency" url:"currency"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CostOverride) GetAmount() float64 {
	if c == nil {
		return 0
	}
	return c.Amount
}

func (c *CostOverride) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *CostOverride) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CostOverride) UnmarshalJSON(data []byte) error {
	type unmarshaler CostOverride
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CostOverride(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CostOverride) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type PrecomputedCost struct {
	// Record time in RFC3339 format with timezone. Defaults to server receive time.
	Timestamp *time.Time           `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Customer  *CustomerAttribution `json:"customer" url:"customer"`
	Product   *ProductAttribution  `json:"product,omitempty" url:"product,omitempty"`
	// Free-form metadata for filtering and analytics.
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	// Cost amount in major units of `currency` (e.g. dollars).
	Amount float64 `json:"amount" url:"amount"`
	// ISO 4217 currency code, e.g. "USD".
	Currency string `json:"currency" url:"currency"`
	// Optional vendor tag for analytics (e.g. "openai", "anthropic"). Not used for pricing in this mode.
	Vendor *string `json:"vendor,omitempty" url:"vendor,omitempty"`
	// Optional model tag for analytics (e.g. "gpt-4o-2024-08-06").
	Model *string `json:"model,omitempty" url:"model,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PrecomputedCost) GetTimestamp() *time.Time {
	if p == nil {
		return nil
	}
	return p.Timestamp
}

func (p *PrecomputedCost) GetCustomer() *CustomerAttribution {
	if p == nil {
		return nil
	}
	return p.Customer
}

func (p *PrecomputedCost) GetProduct() *ProductAttribution {
	if p == nil {
		return nil
	}
	return p.Product
}

func (p *PrecomputedCost) GetMetadata() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.Metadata
}

func (p *PrecomputedCost) GetAmount() float64 {
	if p == nil {
		return 0
	}
	return p.Amount
}

func (p *PrecomputedCost) GetCurrency() string {
	if p == nil {
		return ""
	}
	return p.Currency
}

func (p *PrecomputedCost) GetVendor() *string {
	if p == nil {
		return nil
	}
	return p.Vendor
}

func (p *PrecomputedCost) GetModel() *string {
	if p == nil {
		return nil
	}
	return p.Model
}

func (p *PrecomputedCost) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PrecomputedCost) UnmarshalJSON(data []byte) error {
	type embed PrecomputedCost
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PrecomputedCost(unmarshaler.embed)
	p.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PrecomputedCost) MarshalJSON() ([]byte, error) {
	type embed PrecomputedCost
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*p),
		Timestamp: internal.NewOptionalDateTime(p.Timestamp),
	}
	return json.Marshal(marshaler)
}

func (p *PrecomputedCost) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type TokenUsage struct {
	// Non-cached input tokens. Matches Anthropic's `input_tokens` semantic (does not include cached or cache-creation tokens).
	InputTokens *int `json:"inputTokens,omitempty" url:"inputTokens,omitempty"`
	// Output tokens generated by the model.
	OutputTokens *int `json:"outputTokens,omitempty" url:"outputTokens,omitempty"`
	// Input tokens served from cache (cache hit).
	CacheReadInputTokens *int `json:"cacheReadInputTokens,omitempty" url:"cacheReadInputTokens,omitempty"`
	// Input tokens written to cache on this request (Anthropic prompt caching).
	CacheCreationInputTokens *int `json:"cacheCreationInputTokens,omitempty" url:"cacheCreationInputTokens,omitempty"`
	// Reasoning tokens emitted by reasoning models (o1/o3, Claude extended thinking).
	ReasoningOutputTokens *int `json:"reasoningOutputTokens,omitempty" url:"reasoningOutputTokens,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TokenUsage) GetInputTokens() *int {
	if t == nil {
		return nil
	}
	return t.InputTokens
}

func (t *TokenUsage) GetOutputTokens() *int {
	if t == nil {
		return nil
	}
	return t.OutputTokens
}

func (t *TokenUsage) GetCacheReadInputTokens() *int {
	if t == nil {
		return nil
	}
	return t.CacheReadInputTokens
}

func (t *TokenUsage) GetCacheCreationInputTokens() *int {
	if t == nil {
		return nil
	}
	return t.CacheCreationInputTokens
}

func (t *TokenUsage) GetReasoningOutputTokens() *int {
	if t == nil {
		return nil
	}
	return t.ReasoningOutputTokens
}

func (t *TokenUsage) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TokenUsage) UnmarshalJSON(data []byte) error {
	type unmarshaler TokenUsage
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TokenUsage(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TokenUsage) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type UsageCost struct {
	// Record time in RFC3339 format with timezone. Defaults to server receive time.
	Timestamp *time.Time           `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Customer  *CustomerAttribution `json:"customer" url:"customer"`
	Product   *ProductAttribution  `json:"product,omitempty" url:"product,omitempty"`
	// Free-form metadata for filtering and analytics.
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	// Provider name, used together with `model` to look up pricing (e.g. "openai", "anthropic").
	Vendor string `json:"vendor" url:"vendor"`
	// Exact provider model ID (e.g. "gpt-4o-2024-08-06").
	Model        string        `json:"model" url:"model"`
	Usage        *TokenUsage   `json:"usage" url:"usage"`
	CostOverride *CostOverride `json:"costOverride,omitempty" url:"costOverride,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UsageCost) GetTimestamp() *time.Time {
	if u == nil {
		return nil
	}
	return u.Timestamp
}

func (u *UsageCost) GetCustomer() *CustomerAttribution {
	if u == nil {
		return nil
	}
	return u.Customer
}

func (u *UsageCost) GetProduct() *ProductAttribution {
	if u == nil {
		return nil
	}
	return u.Product
}

func (u *UsageCost) GetMetadata() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.Metadata
}

func (u *UsageCost) GetVendor() string {
	if u == nil {
		return ""
	}
	return u.Vendor
}

func (u *UsageCost) GetModel() string {
	if u == nil {
		return ""
	}
	return u.Model
}

func (u *UsageCost) GetUsage() *TokenUsage {
	if u == nil {
		return nil
	}
	return u.Usage
}

func (u *UsageCost) GetCostOverride() *CostOverride {
	if u == nil {
		return nil
	}
	return u.CostOverride
}

func (u *UsageCost) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UsageCost) UnmarshalJSON(data []byte) error {
	type embed UsageCost
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*u),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*u = UsageCost(unmarshaler.embed)
	u.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UsageCost) MarshalJSON() ([]byte, error) {
	type embed UsageCost
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*u),
		Timestamp: internal.NewOptionalDateTime(u.Timestamp),
	}
	return json.Marshal(marshaler)
}

func (u *UsageCost) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}
