// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/paid-ai/paid-go/internal"
	time "time"
)

type CreateCreditCurrencyRequest struct {
	// Human-readable name shown for this credit currency.
	Name string `json:"name" url:"-"`
	// Stable machine-readable key for this credit currency. Use lowercase letters, numbers, underscores, and hyphens. Keys are unique within an organization.
	Key string `json:"key" url:"-"`
	// Optional description for this credit currency.
	Description *string `json:"description,omitempty" url:"-"`
}

type ListCreditCurrenciesRequest struct {
	// Filter credit currencies by status. Defaults to `all` so archived currencies remain readable after they are archived.
	Status *ListCreditCurrenciesRequestStatus `json:"-" url:"status,omitempty"`
}

type CreditCurrency struct {
	// Unique identifier for this credit currency.
	ID string `json:"id" url:"id"`
	// Human-readable name shown for this credit currency.
	Name string `json:"name" url:"name"`
	// Stable machine-readable key for this credit currency. Keys are unique within an organization.
	Key string `json:"key" url:"key"`
	// Whether this credit currency is active or archived.
	Status CreditCurrencyStatus `json:"status" url:"status"`
	// Optional description for this credit currency.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// When this credit currency was archived. Null means the currency is active.
	ArchivedAt *time.Time `json:"archivedAt,omitempty" url:"archivedAt,omitempty"`
	// When this credit currency was created.
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`
	// When this credit currency was last updated.
	UpdatedAt time.Time `json:"updatedAt" url:"updatedAt"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreditCurrency) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreditCurrency) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreditCurrency) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

func (c *CreditCurrency) GetStatus() CreditCurrencyStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CreditCurrency) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreditCurrency) GetArchivedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.ArchivedAt
}

func (c *CreditCurrency) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CreditCurrency) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

func (c *CreditCurrency) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreditCurrency) UnmarshalJSON(data []byte) error {
	type embed CreditCurrency
	var unmarshaler = struct {
		embed
		ArchivedAt *internal.DateTime `json:"archivedAt,omitempty"`
		CreatedAt  *internal.DateTime `json:"createdAt"`
		UpdatedAt  *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreditCurrency(unmarshaler.embed)
	c.ArchivedAt = unmarshaler.ArchivedAt.TimePtr()
	c.CreatedAt = unmarshaler.CreatedAt.Time()
	c.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreditCurrency) MarshalJSON() ([]byte, error) {
	type embed CreditCurrency
	var marshaler = struct {
		embed
		ArchivedAt *internal.DateTime `json:"archivedAt,omitempty"`
		CreatedAt  *internal.DateTime `json:"createdAt"`
		UpdatedAt  *internal.DateTime `json:"updatedAt"`
	}{
		embed:      embed(*c),
		ArchivedAt: internal.NewOptionalDateTime(c.ArchivedAt),
		CreatedAt:  internal.NewDateTime(c.CreatedAt),
		UpdatedAt:  internal.NewDateTime(c.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (c *CreditCurrency) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreditCurrencyListResponse struct {
	Data []*CreditCurrency `json:"data" url:"data"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreditCurrencyListResponse) GetData() []*CreditCurrency {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreditCurrencyListResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreditCurrencyListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreditCurrencyListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreditCurrencyListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreditCurrencyListResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Whether this credit currency is active or archived.
type CreditCurrencyStatus string

const (
	CreditCurrencyStatusActive   CreditCurrencyStatus = "active"
	CreditCurrencyStatusArchived CreditCurrencyStatus = "archived"
)

func NewCreditCurrencyStatusFromString(s string) (CreditCurrencyStatus, error) {
	switch s {
	case "active":
		return CreditCurrencyStatusActive, nil
	case "archived":
		return CreditCurrencyStatusArchived, nil
	}
	var t CreditCurrencyStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreditCurrencyStatus) Ptr() *CreditCurrencyStatus {
	return &c
}

type ListCreditCurrenciesRequestStatus string

const (
	ListCreditCurrenciesRequestStatusActive   ListCreditCurrenciesRequestStatus = "active"
	ListCreditCurrenciesRequestStatusArchived ListCreditCurrenciesRequestStatus = "archived"
	ListCreditCurrenciesRequestStatusAll      ListCreditCurrenciesRequestStatus = "all"
)

func NewListCreditCurrenciesRequestStatusFromString(s string) (ListCreditCurrenciesRequestStatus, error) {
	switch s {
	case "active":
		return ListCreditCurrenciesRequestStatusActive, nil
	case "archived":
		return ListCreditCurrenciesRequestStatusArchived, nil
	case "all":
		return ListCreditCurrenciesRequestStatusAll, nil
	}
	var t ListCreditCurrenciesRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListCreditCurrenciesRequestStatus) Ptr() *ListCreditCurrenciesRequestStatus {
	return &l
}

// Set to `archived` to archive this credit currency, or `active` to restore it.
type UpdateCreditCurrencyRequestStatus string

const (
	UpdateCreditCurrencyRequestStatusActive   UpdateCreditCurrencyRequestStatus = "active"
	UpdateCreditCurrencyRequestStatusArchived UpdateCreditCurrencyRequestStatus = "archived"
)

func NewUpdateCreditCurrencyRequestStatusFromString(s string) (UpdateCreditCurrencyRequestStatus, error) {
	switch s {
	case "active":
		return UpdateCreditCurrencyRequestStatusActive, nil
	case "archived":
		return UpdateCreditCurrencyRequestStatusArchived, nil
	}
	var t UpdateCreditCurrencyRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateCreditCurrencyRequestStatus) Ptr() *UpdateCreditCurrencyRequestStatus {
	return &u
}

type UpdateCreditCurrencyRequest struct {
	// Credit currency ID.
	ID string `json:"-" url:"-"`
	// Updated description for this credit currency. Use null to clear the description.
	Description *string `json:"description,omitempty" url:"-"`
	// Set to `archived` to archive this credit currency, or `active` to restore it.
	Status *UpdateCreditCurrencyRequestStatus `json:"status,omitempty" url:"-"`
}
