// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/paid-ai/paid-go/internal"
	time "time"
)

type CreateCustomViewRequest struct {
	// Human-readable view name (shown in preview + audit log).
	Name string `json:"name" url:"-"`
	// Optional longer description of what the view shows.
	Description *string `json:"description,omitempty" url:"-"`
	// One or more named queries. Each becomes a separately-keyed result set in the embed.
	Queries []*CustomViewQuery `json:"queries,omitempty" url:"-"`
	// Self-contained HTML document that renders the result sets. Inline ALL CSS/JS/charting libraries — the render sandbox has no network access. It receives the keyed result sets via a `message` event (`data[<queryId>]`) and must not fetch anything itself.
	RenderBundle string `json:"renderBundle" url:"-"`
	// Optional default date range. Required if any query uses the `{period_start:DateTime}` / `{period_end:DateTime}` placeholders. Can be changed later in Paid without re-authoring.
	Period *CreateCustomViewRequestPeriod `json:"period,omitempty" url:"-"`
	// 'customer' (default): data is scoped to one viewing customer and the view is embeddable per-customer. 'organization': data is org-wide; the view is internal-only (visible to org members in Paid, never embeddable).
	Scope *CreateCustomViewRequestScope `json:"scope,omitempty" url:"-"`
}

type GetCustomViewRequest struct {
	DisplayID string `json:"-" url:"-"`
}

type GetCustomViewDataRequest struct {
	DisplayID string `json:"-" url:"-"`
	// Customer to scope the data to (dev/preview only; the embed derives this from the verified token). Required for customer-scoped views; ignored for organization-scoped views (their data is org-wide).
	CustomerID *string `json:"-" url:"customerId,omitempty"`
	// Override the view's default date range for this request only. 'relative' = rolling window (set periodUnit + periodAmount); 'absolute' = fixed range (set periodStart + periodEnd).
	PeriodKind *GetCustomViewDataRequestPeriodKind `json:"-" url:"periodKind,omitempty"`
	// relative override only: unit of the rolling window.
	PeriodUnit *GetCustomViewDataRequestPeriodUnit `json:"-" url:"periodUnit,omitempty"`
	// relative override only: how many units back from today.
	PeriodAmount *int `json:"-" url:"periodAmount,omitempty"`
	// absolute override only: inclusive start date (YYYY-MM-DD).
	PeriodStart *string `json:"-" url:"periodStart,omitempty"`
	// absolute override only: inclusive end date (YYYY-MM-DD).
	PeriodEnd *string `json:"-" url:"periodEnd,omitempty"`
}

type GetCustomViewEmbedTokenRequest struct {
	DisplayID string `json:"-" url:"-"`
	// The customer to scope the view to: external id, Paid display id (cus_…), or internal id.
	CustomerID string `json:"-" url:"customerId"`
	// Token lifetime in seconds (capped at 3600).
	TTLSeconds *int `json:"-" url:"ttlSeconds,omitempty"`
}

type PublishCustomViewRequest struct {
	DisplayID string `json:"-" url:"-"`
}

type CustomView struct {
	// Stable public identifier used in preview/embed URLs.
	DisplayID string `json:"displayId" url:"displayId"`
	Name      string `json:"name" url:"name"`
	// A view is DRAFT until explicitly published. For customer-scoped views, only PUBLISHED views are embeddable and served to end-customers; a DRAFT is not. For organization-scoped views, publishing is only a 'ready to use' marker — both DRAFT and PUBLISHED are visible to your organization's members in Paid (publishing does not change who in the org can see it), and neither is ever embeddable to an end-customer.
	Status CustomViewStatus `json:"status" url:"status"`
	// Absolute URL to open this view in the Paid app for preview. Surface it to the user after creating or publishing a view. Null when the app URL is not configured.
	PreviewURL *string `json:"previewUrl,omitempty" url:"previewUrl,omitempty"`
	// 'customer': data is scoped to one viewing customer and the view is embeddable per-customer. 'organization': data is org-wide and the view is internal-only.
	Scope CustomViewScope `json:"scope" url:"scope"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomView) GetDisplayID() string {
	if c == nil {
		return ""
	}
	return c.DisplayID
}

func (c *CustomView) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomView) GetStatus() CustomViewStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CustomView) GetPreviewURL() *string {
	if c == nil {
		return nil
	}
	return c.PreviewURL
}

func (c *CustomView) GetScope() CustomViewScope {
	if c == nil {
		return ""
	}
	return c.Scope
}

func (c *CustomView) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomView) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomView
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomView(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomView) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CustomViewDetail struct {
	DisplayID   string                 `json:"displayId" url:"displayId"`
	Name        string                 `json:"name" url:"name"`
	Description *string                `json:"description,omitempty" url:"description,omitempty"`
	Status      CustomViewDetailStatus `json:"status" url:"status"`
	// Ids of the result sets the render bundle will receive.
	QueryIDs []string `json:"queryIds" url:"queryIds"`
	// Self-contained HTML document rendered inside the isolated sandbox iframe.
	RenderBundle string `json:"renderBundle" url:"renderBundle"`
	// The view's current default date range, or null if it uses no adjustable period.
	Period *CustomViewDetailPeriod `json:"period,omitempty" url:"period,omitempty"`
	// 'customer': data is scoped to one viewing customer and the view is embeddable per-customer. 'organization': data is org-wide and the view is internal-only.
	Scope CustomViewDetailScope `json:"scope" url:"scope"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomViewDetail) GetDisplayID() string {
	if c == nil {
		return ""
	}
	return c.DisplayID
}

func (c *CustomViewDetail) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomViewDetail) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CustomViewDetail) GetStatus() CustomViewDetailStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CustomViewDetail) GetQueryIDs() []string {
	if c == nil {
		return nil
	}
	return c.QueryIDs
}

func (c *CustomViewDetail) GetRenderBundle() string {
	if c == nil {
		return ""
	}
	return c.RenderBundle
}

func (c *CustomViewDetail) GetPeriod() *CustomViewDetailPeriod {
	if c == nil {
		return nil
	}
	return c.Period
}

func (c *CustomViewDetail) GetScope() CustomViewDetailScope {
	if c == nil {
		return ""
	}
	return c.Scope
}

func (c *CustomViewDetail) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomViewDetail) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomViewDetail
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomViewDetail(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomViewDetail) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// The view's current default date range, or null if it uses no adjustable period.
type CustomViewDetailPeriod struct {
	// 'relative' = a rolling window ending today (set `unit` + `amount`); 'absolute' = a fixed calendar range (set `start` + `end`).
	Kind CustomViewDetailPeriodKind `json:"kind" url:"kind"`
	// relative only: the unit of the rolling window.
	Unit *CustomViewDetailPeriodUnit `json:"unit,omitempty" url:"unit,omitempty"`
	// relative only: how many units back from today (e.g. unit 'day', amount 30 = last 30 days).
	Amount *int `json:"amount,omitempty" url:"amount,omitempty"`
	// absolute only: inclusive start date (YYYY-MM-DD).
	Start *string `json:"start,omitempty" url:"start,omitempty"`
	// absolute only: inclusive end date (YYYY-MM-DD).
	End *string `json:"end,omitempty" url:"end,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomViewDetailPeriod) GetKind() CustomViewDetailPeriodKind {
	if c == nil {
		return ""
	}
	return c.Kind
}

func (c *CustomViewDetailPeriod) GetUnit() *CustomViewDetailPeriodUnit {
	if c == nil {
		return nil
	}
	return c.Unit
}

func (c *CustomViewDetailPeriod) GetAmount() *int {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CustomViewDetailPeriod) GetStart() *string {
	if c == nil {
		return nil
	}
	return c.Start
}

func (c *CustomViewDetailPeriod) GetEnd() *string {
	if c == nil {
		return nil
	}
	return c.End
}

func (c *CustomViewDetailPeriod) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomViewDetailPeriod) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomViewDetailPeriod
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomViewDetailPeriod(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomViewDetailPeriod) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// 'relative' = a rolling window ending today (set `unit` + `amount`); 'absolute' = a fixed calendar range (set `start` + `end`).
type CustomViewDetailPeriodKind string

const (
	CustomViewDetailPeriodKindRelative CustomViewDetailPeriodKind = "relative"
	CustomViewDetailPeriodKindAbsolute CustomViewDetailPeriodKind = "absolute"
)

func NewCustomViewDetailPeriodKindFromString(s string) (CustomViewDetailPeriodKind, error) {
	switch s {
	case "relative":
		return CustomViewDetailPeriodKindRelative, nil
	case "absolute":
		return CustomViewDetailPeriodKindAbsolute, nil
	}
	var t CustomViewDetailPeriodKind
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomViewDetailPeriodKind) Ptr() *CustomViewDetailPeriodKind {
	return &c
}

// relative only: the unit of the rolling window.
type CustomViewDetailPeriodUnit string

const (
	CustomViewDetailPeriodUnitDay   CustomViewDetailPeriodUnit = "day"
	CustomViewDetailPeriodUnitMonth CustomViewDetailPeriodUnit = "month"
	CustomViewDetailPeriodUnitYear  CustomViewDetailPeriodUnit = "year"
)

func NewCustomViewDetailPeriodUnitFromString(s string) (CustomViewDetailPeriodUnit, error) {
	switch s {
	case "day":
		return CustomViewDetailPeriodUnitDay, nil
	case "month":
		return CustomViewDetailPeriodUnitMonth, nil
	case "year":
		return CustomViewDetailPeriodUnitYear, nil
	}
	var t CustomViewDetailPeriodUnit
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomViewDetailPeriodUnit) Ptr() *CustomViewDetailPeriodUnit {
	return &c
}

// 'customer': data is scoped to one viewing customer and the view is embeddable per-customer. 'organization': data is org-wide and the view is internal-only.
type CustomViewDetailScope string

const (
	CustomViewDetailScopeCustomer     CustomViewDetailScope = "customer"
	CustomViewDetailScopeOrganization CustomViewDetailScope = "organization"
)

func NewCustomViewDetailScopeFromString(s string) (CustomViewDetailScope, error) {
	switch s {
	case "customer":
		return CustomViewDetailScopeCustomer, nil
	case "organization":
		return CustomViewDetailScopeOrganization, nil
	}
	var t CustomViewDetailScope
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomViewDetailScope) Ptr() *CustomViewDetailScope {
	return &c
}

type CustomViewDetailStatus string

const (
	CustomViewDetailStatusDraft     CustomViewDetailStatus = "DRAFT"
	CustomViewDetailStatusPublished CustomViewDetailStatus = "PUBLISHED"
)

func NewCustomViewDetailStatusFromString(s string) (CustomViewDetailStatus, error) {
	switch s {
	case "DRAFT":
		return CustomViewDetailStatusDraft, nil
	case "PUBLISHED":
		return CustomViewDetailStatusPublished, nil
	}
	var t CustomViewDetailStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomViewDetailStatus) Ptr() *CustomViewDetailStatus {
	return &c
}

type CustomViewEmbedTokenResponse struct {
	// Short-lived signed token to pass to the embed SDK.
	Token string `json:"token" url:"token"`
	// When the token expires (ISO 8601).
	ExpiresAt time.Time `json:"expiresAt" url:"expiresAt"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomViewEmbedTokenResponse) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}

func (c *CustomViewEmbedTokenResponse) GetExpiresAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.ExpiresAt
}

func (c *CustomViewEmbedTokenResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomViewEmbedTokenResponse) UnmarshalJSON(data []byte) error {
	type embed CustomViewEmbedTokenResponse
	var unmarshaler = struct {
		embed
		ExpiresAt *internal.DateTime `json:"expiresAt"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CustomViewEmbedTokenResponse(unmarshaler.embed)
	c.ExpiresAt = unmarshaler.ExpiresAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomViewEmbedTokenResponse) MarshalJSON() ([]byte, error) {
	type embed CustomViewEmbedTokenResponse
	var marshaler = struct {
		embed
		ExpiresAt *internal.DateTime `json:"expiresAt"`
	}{
		embed:     embed(*c),
		ExpiresAt: internal.NewDateTime(c.ExpiresAt),
	}
	return json.Marshal(marshaler)
}

func (c *CustomViewEmbedTokenResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CustomViewListResponse struct {
	Views []*CustomViewSummary `json:"views" url:"views"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomViewListResponse) GetViews() []*CustomViewSummary {
	if c == nil {
		return nil
	}
	return c.Views
}

func (c *CustomViewListResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomViewListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomViewListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomViewListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomViewListResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CustomViewQuery struct {
	// Stable identifier for this query's result set; the render bundle reads `data[<id>]`.
	ID string `json:"id" url:"id"`
	// A single ClickHouse SELECT (or WITH … SELECT). Do NOT add a customer filter — the database scopes every query to the viewing customer at run time. Return clearly-named columns; bake any date range into WHERE.
	SQL string `json:"sql" url:"sql"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomViewQuery) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CustomViewQuery) GetSQL() string {
	if c == nil {
		return ""
	}
	return c.SQL
}

func (c *CustomViewQuery) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomViewQuery) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomViewQuery
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomViewQuery(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomViewQuery) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// 'customer': data is scoped to one viewing customer and the view is embeddable per-customer. 'organization': data is org-wide and the view is internal-only.
type CustomViewScope string

const (
	CustomViewScopeCustomer     CustomViewScope = "customer"
	CustomViewScopeOrganization CustomViewScope = "organization"
)

func NewCustomViewScopeFromString(s string) (CustomViewScope, error) {
	switch s {
	case "customer":
		return CustomViewScopeCustomer, nil
	case "organization":
		return CustomViewScopeOrganization, nil
	}
	var t CustomViewScope
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomViewScope) Ptr() *CustomViewScope {
	return &c
}

// A view is DRAFT until explicitly published. For customer-scoped views, only PUBLISHED views are embeddable and served to end-customers; a DRAFT is not. For organization-scoped views, publishing is only a 'ready to use' marker — both DRAFT and PUBLISHED are visible to your organization's members in Paid (publishing does not change who in the org can see it), and neither is ever embeddable to an end-customer.
type CustomViewStatus string

const (
	CustomViewStatusDraft     CustomViewStatus = "DRAFT"
	CustomViewStatusPublished CustomViewStatus = "PUBLISHED"
)

func NewCustomViewStatusFromString(s string) (CustomViewStatus, error) {
	switch s {
	case "DRAFT":
		return CustomViewStatusDraft, nil
	case "PUBLISHED":
		return CustomViewStatusPublished, nil
	}
	var t CustomViewStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomViewStatus) Ptr() *CustomViewStatus {
	return &c
}

type CustomViewSummary struct {
	DisplayID   string                  `json:"displayId" url:"displayId"`
	Name        string                  `json:"name" url:"name"`
	Description *string                 `json:"description,omitempty" url:"description,omitempty"`
	Status      CustomViewSummaryStatus `json:"status" url:"status"`
	// How many named queries the view holds.
	QueryCount int `json:"queryCount" url:"queryCount"`
	// The view's default date range, or null if it has none.
	Period *CustomViewSummaryPeriod `json:"period,omitempty" url:"period,omitempty"`
	// ISO 8601 creation timestamp.
	CreatedAt string `json:"createdAt" url:"createdAt"`
	// 'customer': data is scoped to one viewing customer and the view is embeddable per-customer. 'organization': data is org-wide and the view is internal-only.
	Scope CustomViewSummaryScope `json:"scope" url:"scope"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomViewSummary) GetDisplayID() string {
	if c == nil {
		return ""
	}
	return c.DisplayID
}

func (c *CustomViewSummary) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomViewSummary) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CustomViewSummary) GetStatus() CustomViewSummaryStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CustomViewSummary) GetQueryCount() int {
	if c == nil {
		return 0
	}
	return c.QueryCount
}

func (c *CustomViewSummary) GetPeriod() *CustomViewSummaryPeriod {
	if c == nil {
		return nil
	}
	return c.Period
}

func (c *CustomViewSummary) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CustomViewSummary) GetScope() CustomViewSummaryScope {
	if c == nil {
		return ""
	}
	return c.Scope
}

func (c *CustomViewSummary) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomViewSummary) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomViewSummary
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomViewSummary(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomViewSummary) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// The view's default date range, or null if it has none.
type CustomViewSummaryPeriod struct {
	// 'relative' = a rolling window ending today (set `unit` + `amount`); 'absolute' = a fixed calendar range (set `start` + `end`).
	Kind CustomViewSummaryPeriodKind `json:"kind" url:"kind"`
	// relative only: the unit of the rolling window.
	Unit *CustomViewSummaryPeriodUnit `json:"unit,omitempty" url:"unit,omitempty"`
	// relative only: how many units back from today (e.g. unit 'day', amount 30 = last 30 days).
	Amount *int `json:"amount,omitempty" url:"amount,omitempty"`
	// absolute only: inclusive start date (YYYY-MM-DD).
	Start *string `json:"start,omitempty" url:"start,omitempty"`
	// absolute only: inclusive end date (YYYY-MM-DD).
	End *string `json:"end,omitempty" url:"end,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomViewSummaryPeriod) GetKind() CustomViewSummaryPeriodKind {
	if c == nil {
		return ""
	}
	return c.Kind
}

func (c *CustomViewSummaryPeriod) GetUnit() *CustomViewSummaryPeriodUnit {
	if c == nil {
		return nil
	}
	return c.Unit
}

func (c *CustomViewSummaryPeriod) GetAmount() *int {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CustomViewSummaryPeriod) GetStart() *string {
	if c == nil {
		return nil
	}
	return c.Start
}

func (c *CustomViewSummaryPeriod) GetEnd() *string {
	if c == nil {
		return nil
	}
	return c.End
}

func (c *CustomViewSummaryPeriod) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomViewSummaryPeriod) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomViewSummaryPeriod
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomViewSummaryPeriod(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomViewSummaryPeriod) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// 'relative' = a rolling window ending today (set `unit` + `amount`); 'absolute' = a fixed calendar range (set `start` + `end`).
type CustomViewSummaryPeriodKind string

const (
	CustomViewSummaryPeriodKindRelative CustomViewSummaryPeriodKind = "relative"
	CustomViewSummaryPeriodKindAbsolute CustomViewSummaryPeriodKind = "absolute"
)

func NewCustomViewSummaryPeriodKindFromString(s string) (CustomViewSummaryPeriodKind, error) {
	switch s {
	case "relative":
		return CustomViewSummaryPeriodKindRelative, nil
	case "absolute":
		return CustomViewSummaryPeriodKindAbsolute, nil
	}
	var t CustomViewSummaryPeriodKind
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomViewSummaryPeriodKind) Ptr() *CustomViewSummaryPeriodKind {
	return &c
}

// relative only: the unit of the rolling window.
type CustomViewSummaryPeriodUnit string

const (
	CustomViewSummaryPeriodUnitDay   CustomViewSummaryPeriodUnit = "day"
	CustomViewSummaryPeriodUnitMonth CustomViewSummaryPeriodUnit = "month"
	CustomViewSummaryPeriodUnitYear  CustomViewSummaryPeriodUnit = "year"
)

func NewCustomViewSummaryPeriodUnitFromString(s string) (CustomViewSummaryPeriodUnit, error) {
	switch s {
	case "day":
		return CustomViewSummaryPeriodUnitDay, nil
	case "month":
		return CustomViewSummaryPeriodUnitMonth, nil
	case "year":
		return CustomViewSummaryPeriodUnitYear, nil
	}
	var t CustomViewSummaryPeriodUnit
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomViewSummaryPeriodUnit) Ptr() *CustomViewSummaryPeriodUnit {
	return &c
}

// 'customer': data is scoped to one viewing customer and the view is embeddable per-customer. 'organization': data is org-wide and the view is internal-only.
type CustomViewSummaryScope string

const (
	CustomViewSummaryScopeCustomer     CustomViewSummaryScope = "customer"
	CustomViewSummaryScopeOrganization CustomViewSummaryScope = "organization"
)

func NewCustomViewSummaryScopeFromString(s string) (CustomViewSummaryScope, error) {
	switch s {
	case "customer":
		return CustomViewSummaryScopeCustomer, nil
	case "organization":
		return CustomViewSummaryScopeOrganization, nil
	}
	var t CustomViewSummaryScope
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomViewSummaryScope) Ptr() *CustomViewSummaryScope {
	return &c
}

type CustomViewSummaryStatus string

const (
	CustomViewSummaryStatusDraft     CustomViewSummaryStatus = "DRAFT"
	CustomViewSummaryStatusPublished CustomViewSummaryStatus = "PUBLISHED"
)

func NewCustomViewSummaryStatusFromString(s string) (CustomViewSummaryStatus, error) {
	switch s {
	case "DRAFT":
		return CustomViewSummaryStatusDraft, nil
	case "PUBLISHED":
		return CustomViewSummaryStatusPublished, nil
	}
	var t CustomViewSummaryStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomViewSummaryStatus) Ptr() *CustomViewSummaryStatus {
	return &c
}

type RenderBundleEdit struct {
	// Exact text to find in the CURRENT stored bundle (fetch it via getCustomViewAuthoring first — it may have been hand-edited). Must match exactly once unless `replaceAll` is true; include enough surrounding context to make it unique.
	OldText string `json:"oldText" url:"oldText"`
	// Replacement text. May be empty to delete the matched text.
	NewText string `json:"newText" url:"newText"`
	// Replace every occurrence instead of requiring a unique match (e.g. renaming a variable or color). Default false.
	ReplaceAll *bool `json:"replaceAll,omitempty" url:"replaceAll,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RenderBundleEdit) GetOldText() string {
	if r == nil {
		return ""
	}
	return r.OldText
}

func (r *RenderBundleEdit) GetNewText() string {
	if r == nil {
		return ""
	}
	return r.NewText
}

func (r *RenderBundleEdit) GetReplaceAll() *bool {
	if r == nil {
		return nil
	}
	return r.ReplaceAll
}

func (r *RenderBundleEdit) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RenderBundleEdit) UnmarshalJSON(data []byte) error {
	type unmarshaler RenderBundleEdit
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RenderBundleEdit(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RenderBundleEdit) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type ViewDataResponse struct {
	// Result sets keyed by query id. Each value is an array of row objects (column name → value); 64-bit integers are returned as JSON strings to preserve precision.
	Data map[string][]map[string]interface{} `json:"data" url:"data"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *ViewDataResponse) GetData() map[string][]map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *ViewDataResponse) GetExtraProperties() map[string]interface{} {
	return v.extraProperties
}

func (v *ViewDataResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ViewDataResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = ViewDataResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *ViewDataResponse) String() string {
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

// Optional default date range. Required if any query uses the `{period_start:DateTime}` / `{period_end:DateTime}` placeholders. Can be changed later in Paid without re-authoring.
type CreateCustomViewRequestPeriod struct {
	// 'relative' = a rolling window ending today (set `unit` + `amount`); 'absolute' = a fixed calendar range (set `start` + `end`).
	Kind CreateCustomViewRequestPeriodKind `json:"kind" url:"kind"`
	// relative only: the unit of the rolling window.
	Unit *CreateCustomViewRequestPeriodUnit `json:"unit,omitempty" url:"unit,omitempty"`
	// relative only: how many units back from today (e.g. unit 'day', amount 30 = last 30 days).
	Amount *int `json:"amount,omitempty" url:"amount,omitempty"`
	// absolute only: inclusive start date (YYYY-MM-DD).
	Start *string `json:"start,omitempty" url:"start,omitempty"`
	// absolute only: inclusive end date (YYYY-MM-DD).
	End *string `json:"end,omitempty" url:"end,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateCustomViewRequestPeriod) GetKind() CreateCustomViewRequestPeriodKind {
	if c == nil {
		return ""
	}
	return c.Kind
}

func (c *CreateCustomViewRequestPeriod) GetUnit() *CreateCustomViewRequestPeriodUnit {
	if c == nil {
		return nil
	}
	return c.Unit
}

func (c *CreateCustomViewRequestPeriod) GetAmount() *int {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CreateCustomViewRequestPeriod) GetStart() *string {
	if c == nil {
		return nil
	}
	return c.Start
}

func (c *CreateCustomViewRequestPeriod) GetEnd() *string {
	if c == nil {
		return nil
	}
	return c.End
}

func (c *CreateCustomViewRequestPeriod) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateCustomViewRequestPeriod) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateCustomViewRequestPeriod
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateCustomViewRequestPeriod(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateCustomViewRequestPeriod) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// 'relative' = a rolling window ending today (set `unit` + `amount`); 'absolute' = a fixed calendar range (set `start` + `end`).
type CreateCustomViewRequestPeriodKind string

const (
	CreateCustomViewRequestPeriodKindRelative CreateCustomViewRequestPeriodKind = "relative"
	CreateCustomViewRequestPeriodKindAbsolute CreateCustomViewRequestPeriodKind = "absolute"
)

func NewCreateCustomViewRequestPeriodKindFromString(s string) (CreateCustomViewRequestPeriodKind, error) {
	switch s {
	case "relative":
		return CreateCustomViewRequestPeriodKindRelative, nil
	case "absolute":
		return CreateCustomViewRequestPeriodKindAbsolute, nil
	}
	var t CreateCustomViewRequestPeriodKind
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateCustomViewRequestPeriodKind) Ptr() *CreateCustomViewRequestPeriodKind {
	return &c
}

// relative only: the unit of the rolling window.
type CreateCustomViewRequestPeriodUnit string

const (
	CreateCustomViewRequestPeriodUnitDay   CreateCustomViewRequestPeriodUnit = "day"
	CreateCustomViewRequestPeriodUnitMonth CreateCustomViewRequestPeriodUnit = "month"
	CreateCustomViewRequestPeriodUnitYear  CreateCustomViewRequestPeriodUnit = "year"
)

func NewCreateCustomViewRequestPeriodUnitFromString(s string) (CreateCustomViewRequestPeriodUnit, error) {
	switch s {
	case "day":
		return CreateCustomViewRequestPeriodUnitDay, nil
	case "month":
		return CreateCustomViewRequestPeriodUnitMonth, nil
	case "year":
		return CreateCustomViewRequestPeriodUnitYear, nil
	}
	var t CreateCustomViewRequestPeriodUnit
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateCustomViewRequestPeriodUnit) Ptr() *CreateCustomViewRequestPeriodUnit {
	return &c
}

// 'customer' (default): data is scoped to one viewing customer and the view is embeddable per-customer. 'organization': data is org-wide; the view is internal-only (visible to org members in Paid, never embeddable).
type CreateCustomViewRequestScope string

const (
	CreateCustomViewRequestScopeCustomer     CreateCustomViewRequestScope = "customer"
	CreateCustomViewRequestScopeOrganization CreateCustomViewRequestScope = "organization"
)

func NewCreateCustomViewRequestScopeFromString(s string) (CreateCustomViewRequestScope, error) {
	switch s {
	case "customer":
		return CreateCustomViewRequestScopeCustomer, nil
	case "organization":
		return CreateCustomViewRequestScopeOrganization, nil
	}
	var t CreateCustomViewRequestScope
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateCustomViewRequestScope) Ptr() *CreateCustomViewRequestScope {
	return &c
}

type GetCustomViewDataRequestPeriodKind string

const (
	GetCustomViewDataRequestPeriodKindRelative GetCustomViewDataRequestPeriodKind = "relative"
	GetCustomViewDataRequestPeriodKindAbsolute GetCustomViewDataRequestPeriodKind = "absolute"
)

func NewGetCustomViewDataRequestPeriodKindFromString(s string) (GetCustomViewDataRequestPeriodKind, error) {
	switch s {
	case "relative":
		return GetCustomViewDataRequestPeriodKindRelative, nil
	case "absolute":
		return GetCustomViewDataRequestPeriodKindAbsolute, nil
	}
	var t GetCustomViewDataRequestPeriodKind
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetCustomViewDataRequestPeriodKind) Ptr() *GetCustomViewDataRequestPeriodKind {
	return &g
}

type GetCustomViewDataRequestPeriodUnit string

const (
	GetCustomViewDataRequestPeriodUnitDay   GetCustomViewDataRequestPeriodUnit = "day"
	GetCustomViewDataRequestPeriodUnitMonth GetCustomViewDataRequestPeriodUnit = "month"
	GetCustomViewDataRequestPeriodUnitYear  GetCustomViewDataRequestPeriodUnit = "year"
)

func NewGetCustomViewDataRequestPeriodUnitFromString(s string) (GetCustomViewDataRequestPeriodUnit, error) {
	switch s {
	case "day":
		return GetCustomViewDataRequestPeriodUnitDay, nil
	case "month":
		return GetCustomViewDataRequestPeriodUnitMonth, nil
	case "year":
		return GetCustomViewDataRequestPeriodUnitYear, nil
	}
	var t GetCustomViewDataRequestPeriodUnit
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetCustomViewDataRequestPeriodUnit) Ptr() *GetCustomViewDataRequestPeriodUnit {
	return &g
}

// Default date range for the view's queries. Use `{period_start:DateTime}` / `{period_end:DateTime}` placeholders in your SQL to make the range adjustable. Either relative (unit+amount) or absolute (start+end).
type UpdateCustomViewPeriodRequestPeriod struct {
	// 'relative' = a rolling window ending today (set `unit` + `amount`); 'absolute' = a fixed calendar range (set `start` + `end`).
	Kind UpdateCustomViewPeriodRequestPeriodKind `json:"kind" url:"kind"`
	// relative only: the unit of the rolling window.
	Unit *UpdateCustomViewPeriodRequestPeriodUnit `json:"unit,omitempty" url:"unit,omitempty"`
	// relative only: how many units back from today (e.g. unit 'day', amount 30 = last 30 days).
	Amount *int `json:"amount,omitempty" url:"amount,omitempty"`
	// absolute only: inclusive start date (YYYY-MM-DD).
	Start *string `json:"start,omitempty" url:"start,omitempty"`
	// absolute only: inclusive end date (YYYY-MM-DD).
	End *string `json:"end,omitempty" url:"end,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateCustomViewPeriodRequestPeriod) GetKind() UpdateCustomViewPeriodRequestPeriodKind {
	if u == nil {
		return ""
	}
	return u.Kind
}

func (u *UpdateCustomViewPeriodRequestPeriod) GetUnit() *UpdateCustomViewPeriodRequestPeriodUnit {
	if u == nil {
		return nil
	}
	return u.Unit
}

func (u *UpdateCustomViewPeriodRequestPeriod) GetAmount() *int {
	if u == nil {
		return nil
	}
	return u.Amount
}

func (u *UpdateCustomViewPeriodRequestPeriod) GetStart() *string {
	if u == nil {
		return nil
	}
	return u.Start
}

func (u *UpdateCustomViewPeriodRequestPeriod) GetEnd() *string {
	if u == nil {
		return nil
	}
	return u.End
}

func (u *UpdateCustomViewPeriodRequestPeriod) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateCustomViewPeriodRequestPeriod) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateCustomViewPeriodRequestPeriod
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateCustomViewPeriodRequestPeriod(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateCustomViewPeriodRequestPeriod) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// 'relative' = a rolling window ending today (set `unit` + `amount`); 'absolute' = a fixed calendar range (set `start` + `end`).
type UpdateCustomViewPeriodRequestPeriodKind string

const (
	UpdateCustomViewPeriodRequestPeriodKindRelative UpdateCustomViewPeriodRequestPeriodKind = "relative"
	UpdateCustomViewPeriodRequestPeriodKindAbsolute UpdateCustomViewPeriodRequestPeriodKind = "absolute"
)

func NewUpdateCustomViewPeriodRequestPeriodKindFromString(s string) (UpdateCustomViewPeriodRequestPeriodKind, error) {
	switch s {
	case "relative":
		return UpdateCustomViewPeriodRequestPeriodKindRelative, nil
	case "absolute":
		return UpdateCustomViewPeriodRequestPeriodKindAbsolute, nil
	}
	var t UpdateCustomViewPeriodRequestPeriodKind
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateCustomViewPeriodRequestPeriodKind) Ptr() *UpdateCustomViewPeriodRequestPeriodKind {
	return &u
}

// relative only: the unit of the rolling window.
type UpdateCustomViewPeriodRequestPeriodUnit string

const (
	UpdateCustomViewPeriodRequestPeriodUnitDay   UpdateCustomViewPeriodRequestPeriodUnit = "day"
	UpdateCustomViewPeriodRequestPeriodUnitMonth UpdateCustomViewPeriodRequestPeriodUnit = "month"
	UpdateCustomViewPeriodRequestPeriodUnitYear  UpdateCustomViewPeriodRequestPeriodUnit = "year"
)

func NewUpdateCustomViewPeriodRequestPeriodUnitFromString(s string) (UpdateCustomViewPeriodRequestPeriodUnit, error) {
	switch s {
	case "day":
		return UpdateCustomViewPeriodRequestPeriodUnitDay, nil
	case "month":
		return UpdateCustomViewPeriodRequestPeriodUnitMonth, nil
	case "year":
		return UpdateCustomViewPeriodRequestPeriodUnitYear, nil
	}
	var t UpdateCustomViewPeriodRequestPeriodUnit
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateCustomViewPeriodRequestPeriodUnit) Ptr() *UpdateCustomViewPeriodRequestPeriodUnit {
	return &u
}

type UpdateCustomViewRequest struct {
	DisplayID string `json:"-" url:"-"`
	// New human-readable view name.
	Name *string `json:"name,omitempty" url:"-"`
	// New description; pass null to clear it.
	Description *string `json:"description,omitempty" url:"-"`
	// Full replacement of the view's query list. Each SQL is re-validated (SELECT-only) exactly like createCustomView. For changing one or two queries, prefer `queryUpserts`/`queryRemovals` instead. Cannot be combined with them.
	Queries []*CustomViewQuery `json:"queries,omitempty" url:"-"`
	// Replacement render bundle. Re-validated (size cap, self-contained, paid:data listener) exactly like createCustomView. For small changes, prefer `bundleEdits` instead. Cannot be combined with `bundleEdits`.
	RenderBundle *string `json:"renderBundle,omitempty" url:"-"`
	// PREFERRED for revisions: exact search-and-replace edits applied in order to the stored render bundle, so you send only the changed text instead of re-transmitting the whole bundle. The edited result passes the same validation as a full replacement. Cannot be combined with `renderBundle`.
	BundleEdits []*RenderBundleEdit `json:"bundleEdits,omitempty" url:"-"`
	// PREFERRED for revisions: per-query changes — each entry replaces the stored query with the same id, or is appended as a new query. Queries not mentioned are left unchanged. Cannot be combined with `queries`.
	QueryUpserts []*CustomViewQuery `json:"queryUpserts,omitempty" url:"-"`
	// Ids of stored queries to remove (applied before `queryUpserts`). Rejected if an id does not exist. Cannot be combined with `queries`.
	QueryRemovals []string `json:"queryRemovals,omitempty" url:"-"`
}

type UpdateCustomViewPeriodRequest struct {
	DisplayID string `json:"-" url:"-"`
	// Default date range for the view's queries. Use `{period_start:DateTime}` / `{period_end:DateTime}` placeholders in your SQL to make the range adjustable. Either relative (unit+amount) or absolute (start+end).
	Period *UpdateCustomViewPeriodRequestPeriod `json:"period,omitempty" url:"-"`
}
