// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/paid-ai/paid-go/internal"
)

type CustomerCreate struct {
	Name            string           `json:"name" url:"-"`
	ExternalId      *string          `json:"externalId,omitempty" url:"-"`
	Phone           *string          `json:"phone,omitempty" url:"-"`
	EmployeeCount   *float64         `json:"employeeCount,omitempty" url:"-"`
	AnnualRevenue   *float64         `json:"annualRevenue,omitempty" url:"-"`
	TaxExemptStatus *TaxExemptStatus `json:"taxExemptStatus,omitempty" url:"-"`
	CreationSource  *CreationSource  `json:"creationSource,omitempty" url:"-"`
	Website         *string          `json:"website,omitempty" url:"-"`
	BillingAddress  *Address         `json:"billingAddress,omitempty" url:"-"`
}

type CustomerUpdate struct {
	Name            *string          `json:"name,omitempty" url:"name,omitempty"`
	ExternalId      *string          `json:"externalId,omitempty" url:"externalId,omitempty"`
	Phone           *string          `json:"phone,omitempty" url:"phone,omitempty"`
	EmployeeCount   *float64         `json:"employeeCount,omitempty" url:"employeeCount,omitempty"`
	AnnualRevenue   *float64         `json:"annualRevenue,omitempty" url:"annualRevenue,omitempty"`
	TaxExemptStatus *TaxExemptStatus `json:"taxExemptStatus,omitempty" url:"taxExemptStatus,omitempty"`
	CreationSource  *CreationSource  `json:"creationSource,omitempty" url:"creationSource,omitempty"`
	Website         *string          `json:"website,omitempty" url:"website,omitempty"`
	BillingAddress  *Address         `json:"billingAddress,omitempty" url:"billingAddress,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomerUpdate) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CustomerUpdate) GetExternalId() *string {
	if c == nil {
		return nil
	}
	return c.ExternalId
}

func (c *CustomerUpdate) GetPhone() *string {
	if c == nil {
		return nil
	}
	return c.Phone
}

func (c *CustomerUpdate) GetEmployeeCount() *float64 {
	if c == nil {
		return nil
	}
	return c.EmployeeCount
}

func (c *CustomerUpdate) GetAnnualRevenue() *float64 {
	if c == nil {
		return nil
	}
	return c.AnnualRevenue
}

func (c *CustomerUpdate) GetTaxExemptStatus() *TaxExemptStatus {
	if c == nil {
		return nil
	}
	return c.TaxExemptStatus
}

func (c *CustomerUpdate) GetCreationSource() *CreationSource {
	if c == nil {
		return nil
	}
	return c.CreationSource
}

func (c *CustomerUpdate) GetWebsite() *string {
	if c == nil {
		return nil
	}
	return c.Website
}

func (c *CustomerUpdate) GetBillingAddress() *Address {
	if c == nil {
		return nil
	}
	return c.BillingAddress
}

func (c *CustomerUpdate) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CustomerUpdate) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomerUpdate
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomerUpdate(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerUpdate) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
