// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/paid-ai/paid-go/internal"
	time "time"
)

type GetInvoiceByIDRequest struct {
	ID string `json:"-" url:"-"`
}

type GetInvoiceLinesRequest struct {
	ID     string `json:"-" url:"-"`
	Limit  *int   `json:"-" url:"limit,omitempty"`
	Offset *int   `json:"-" url:"offset,omitempty"`
}

type ListInvoicesRequest struct {
	Limit  *int `json:"-" url:"limit,omitempty"`
	Offset *int `json:"-" url:"offset,omitempty"`
}

type Invoice struct {
	ID                       string                 `json:"id" url:"id"`
	DisplayNumber            *string                `json:"displayNumber,omitempty" url:"displayNumber,omitempty"`
	OrderID                  *string                `json:"orderId,omitempty" url:"orderId,omitempty"`
	CustomerID               string                 `json:"customerId" url:"customerId"`
	Status                   InvoiceStatus          `json:"status" url:"status"`
	PaymentStatus            InvoicePaymentStatus   `json:"paymentStatus" url:"paymentStatus"`
	Source                   InvoiceSource          `json:"source" url:"source"`
	StartDate                time.Time              `json:"startDate" url:"startDate"`
	EndDate                  *time.Time             `json:"endDate,omitempty" url:"endDate,omitempty"`
	IssueDate                time.Time              `json:"issueDate" url:"issueDate"`
	PostedDate               *time.Time             `json:"postedDate,omitempty" url:"postedDate,omitempty"`
	DueDate                  *time.Time             `json:"dueDate,omitempty" url:"dueDate,omitempty"`
	Currency                 string                 `json:"currency" url:"currency"`
	TaxAmount                float64                `json:"taxAmount" url:"taxAmount"`
	TaxRate                  float64                `json:"taxRate" url:"taxRate"`
	TaxStatus                InvoiceTaxStatus       `json:"taxStatus" url:"taxStatus"`
	InvoiceTotalExcludingTax float64                `json:"invoiceTotalExcludingTax" url:"invoiceTotalExcludingTax"`
	InvoiceTotal             float64                `json:"invoiceTotal" url:"invoiceTotal"`
	AmountDue                float64                `json:"amountDue" url:"amountDue"`
	AmountPaid               float64                `json:"amountPaid" url:"amountPaid"`
	AmountRemaining          float64                `json:"amountRemaining" url:"amountRemaining"`
	CreditNotesTotal         float64                `json:"creditNotesTotal" url:"creditNotesTotal"`
	Metadata                 map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	CreatedAt                time.Time              `json:"createdAt" url:"createdAt"`
	UpdatedAt                time.Time              `json:"updatedAt" url:"updatedAt"`
	PaymentLink              *string                `json:"paymentLink,omitempty" url:"paymentLink,omitempty"`
	DisputeLink              *string                `json:"disputeLink,omitempty" url:"disputeLink,omitempty"`
	PublicURLToken           *string                `json:"publicUrlToken,omitempty" url:"publicUrlToken,omitempty"`
	TaxExempt                bool                   `json:"taxExempt" url:"taxExempt"`
	BillingContactID         *string                `json:"billingContactId,omitempty" url:"billingContactId,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *Invoice) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *Invoice) GetDisplayNumber() *string {
	if i == nil {
		return nil
	}
	return i.DisplayNumber
}

func (i *Invoice) GetOrderID() *string {
	if i == nil {
		return nil
	}
	return i.OrderID
}

func (i *Invoice) GetCustomerID() string {
	if i == nil {
		return ""
	}
	return i.CustomerID
}

func (i *Invoice) GetStatus() InvoiceStatus {
	if i == nil {
		return ""
	}
	return i.Status
}

func (i *Invoice) GetPaymentStatus() InvoicePaymentStatus {
	if i == nil {
		return ""
	}
	return i.PaymentStatus
}

func (i *Invoice) GetSource() InvoiceSource {
	if i == nil {
		return ""
	}
	return i.Source
}

func (i *Invoice) GetStartDate() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.StartDate
}

func (i *Invoice) GetEndDate() *time.Time {
	if i == nil {
		return nil
	}
	return i.EndDate
}

func (i *Invoice) GetIssueDate() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.IssueDate
}

func (i *Invoice) GetPostedDate() *time.Time {
	if i == nil {
		return nil
	}
	return i.PostedDate
}

func (i *Invoice) GetDueDate() *time.Time {
	if i == nil {
		return nil
	}
	return i.DueDate
}

func (i *Invoice) GetCurrency() string {
	if i == nil {
		return ""
	}
	return i.Currency
}

func (i *Invoice) GetTaxAmount() float64 {
	if i == nil {
		return 0
	}
	return i.TaxAmount
}

func (i *Invoice) GetTaxRate() float64 {
	if i == nil {
		return 0
	}
	return i.TaxRate
}

func (i *Invoice) GetTaxStatus() InvoiceTaxStatus {
	if i == nil {
		return ""
	}
	return i.TaxStatus
}

func (i *Invoice) GetInvoiceTotalExcludingTax() float64 {
	if i == nil {
		return 0
	}
	return i.InvoiceTotalExcludingTax
}

func (i *Invoice) GetInvoiceTotal() float64 {
	if i == nil {
		return 0
	}
	return i.InvoiceTotal
}

func (i *Invoice) GetAmountDue() float64 {
	if i == nil {
		return 0
	}
	return i.AmountDue
}

func (i *Invoice) GetAmountPaid() float64 {
	if i == nil {
		return 0
	}
	return i.AmountPaid
}

func (i *Invoice) GetAmountRemaining() float64 {
	if i == nil {
		return 0
	}
	return i.AmountRemaining
}

func (i *Invoice) GetCreditNotesTotal() float64 {
	if i == nil {
		return 0
	}
	return i.CreditNotesTotal
}

func (i *Invoice) GetMetadata() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.Metadata
}

func (i *Invoice) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}

func (i *Invoice) GetUpdatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.UpdatedAt
}

func (i *Invoice) GetPaymentLink() *string {
	if i == nil {
		return nil
	}
	return i.PaymentLink
}

func (i *Invoice) GetDisputeLink() *string {
	if i == nil {
		return nil
	}
	return i.DisputeLink
}

func (i *Invoice) GetPublicURLToken() *string {
	if i == nil {
		return nil
	}
	return i.PublicURLToken
}

func (i *Invoice) GetTaxExempt() bool {
	if i == nil {
		return false
	}
	return i.TaxExempt
}

func (i *Invoice) GetBillingContactID() *string {
	if i == nil {
		return nil
	}
	return i.BillingContactID
}

func (i *Invoice) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *Invoice) UnmarshalJSON(data []byte) error {
	type embed Invoice
	var unmarshaler = struct {
		embed
		StartDate  *internal.DateTime `json:"startDate"`
		EndDate    *internal.DateTime `json:"endDate,omitempty"`
		IssueDate  *internal.DateTime `json:"issueDate"`
		PostedDate *internal.DateTime `json:"postedDate,omitempty"`
		DueDate    *internal.DateTime `json:"dueDate,omitempty"`
		CreatedAt  *internal.DateTime `json:"createdAt"`
		UpdatedAt  *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = Invoice(unmarshaler.embed)
	i.StartDate = unmarshaler.StartDate.Time()
	i.EndDate = unmarshaler.EndDate.TimePtr()
	i.IssueDate = unmarshaler.IssueDate.Time()
	i.PostedDate = unmarshaler.PostedDate.TimePtr()
	i.DueDate = unmarshaler.DueDate.TimePtr()
	i.CreatedAt = unmarshaler.CreatedAt.Time()
	i.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *Invoice) MarshalJSON() ([]byte, error) {
	type embed Invoice
	var marshaler = struct {
		embed
		StartDate  *internal.DateTime `json:"startDate"`
		EndDate    *internal.DateTime `json:"endDate,omitempty"`
		IssueDate  *internal.DateTime `json:"issueDate"`
		PostedDate *internal.DateTime `json:"postedDate,omitempty"`
		DueDate    *internal.DateTime `json:"dueDate,omitempty"`
		CreatedAt  *internal.DateTime `json:"createdAt"`
		UpdatedAt  *internal.DateTime `json:"updatedAt"`
	}{
		embed:      embed(*i),
		StartDate:  internal.NewDateTime(i.StartDate),
		EndDate:    internal.NewOptionalDateTime(i.EndDate),
		IssueDate:  internal.NewDateTime(i.IssueDate),
		PostedDate: internal.NewOptionalDateTime(i.PostedDate),
		DueDate:    internal.NewOptionalDateTime(i.DueDate),
		CreatedAt:  internal.NewDateTime(i.CreatedAt),
		UpdatedAt:  internal.NewDateTime(i.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (i *Invoice) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type InvoiceLine struct {
	ID                   string                   `json:"id" url:"id"`
	OrderID              *string                  `json:"orderId,omitempty" url:"orderId,omitempty"`
	OrderLineID          *string                  `json:"orderLineId,omitempty" url:"orderLineId,omitempty"`
	OrderLineAttributeID *string                  `json:"orderLineAttributeId,omitempty" url:"orderLineAttributeId,omitempty"`
	StartDate            time.Time                `json:"startDate" url:"startDate"`
	EndDate              time.Time                `json:"endDate" url:"endDate"`
	PaymentStatus        InvoiceLinePaymentStatus `json:"paymentStatus" url:"paymentStatus"`
	Quantity             int                      `json:"quantity" url:"quantity"`
	TotalPriceBeforeTax  float64                  `json:"totalPriceBeforeTax" url:"totalPriceBeforeTax"`
	Tax                  float64                  `json:"tax" url:"tax"`
	TaxRate              float64                  `json:"taxRate" url:"taxRate"`
	TotalPriceAfterTax   float64                  `json:"totalPriceAfterTax" url:"totalPriceAfterTax"`
	Currency             string                   `json:"currency" url:"currency"`
	Description          string                   `json:"description" url:"description"`
	BalanceAmount        float64                  `json:"balanceAmount" url:"balanceAmount"`
	CreditedAmount       float64                  `json:"creditedAmount" url:"creditedAmount"`
	CreatedAt            time.Time                `json:"createdAt" url:"createdAt"`
	UpdatedAt            time.Time                `json:"updatedAt" url:"updatedAt"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InvoiceLine) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *InvoiceLine) GetOrderID() *string {
	if i == nil {
		return nil
	}
	return i.OrderID
}

func (i *InvoiceLine) GetOrderLineID() *string {
	if i == nil {
		return nil
	}
	return i.OrderLineID
}

func (i *InvoiceLine) GetOrderLineAttributeID() *string {
	if i == nil {
		return nil
	}
	return i.OrderLineAttributeID
}

func (i *InvoiceLine) GetStartDate() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.StartDate
}

func (i *InvoiceLine) GetEndDate() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.EndDate
}

func (i *InvoiceLine) GetPaymentStatus() InvoiceLinePaymentStatus {
	if i == nil {
		return ""
	}
	return i.PaymentStatus
}

func (i *InvoiceLine) GetQuantity() int {
	if i == nil {
		return 0
	}
	return i.Quantity
}

func (i *InvoiceLine) GetTotalPriceBeforeTax() float64 {
	if i == nil {
		return 0
	}
	return i.TotalPriceBeforeTax
}

func (i *InvoiceLine) GetTax() float64 {
	if i == nil {
		return 0
	}
	return i.Tax
}

func (i *InvoiceLine) GetTaxRate() float64 {
	if i == nil {
		return 0
	}
	return i.TaxRate
}

func (i *InvoiceLine) GetTotalPriceAfterTax() float64 {
	if i == nil {
		return 0
	}
	return i.TotalPriceAfterTax
}

func (i *InvoiceLine) GetCurrency() string {
	if i == nil {
		return ""
	}
	return i.Currency
}

func (i *InvoiceLine) GetDescription() string {
	if i == nil {
		return ""
	}
	return i.Description
}

func (i *InvoiceLine) GetBalanceAmount() float64 {
	if i == nil {
		return 0
	}
	return i.BalanceAmount
}

func (i *InvoiceLine) GetCreditedAmount() float64 {
	if i == nil {
		return 0
	}
	return i.CreditedAmount
}

func (i *InvoiceLine) GetCreatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.CreatedAt
}

func (i *InvoiceLine) GetUpdatedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.UpdatedAt
}

func (i *InvoiceLine) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *InvoiceLine) UnmarshalJSON(data []byte) error {
	type embed InvoiceLine
	var unmarshaler = struct {
		embed
		StartDate *internal.DateTime `json:"startDate"`
		EndDate   *internal.DateTime `json:"endDate"`
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = InvoiceLine(unmarshaler.embed)
	i.StartDate = unmarshaler.StartDate.Time()
	i.EndDate = unmarshaler.EndDate.Time()
	i.CreatedAt = unmarshaler.CreatedAt.Time()
	i.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InvoiceLine) MarshalJSON() ([]byte, error) {
	type embed InvoiceLine
	var marshaler = struct {
		embed
		StartDate *internal.DateTime `json:"startDate"`
		EndDate   *internal.DateTime `json:"endDate"`
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*i),
		StartDate: internal.NewDateTime(i.StartDate),
		EndDate:   internal.NewDateTime(i.EndDate),
		CreatedAt: internal.NewDateTime(i.CreatedAt),
		UpdatedAt: internal.NewDateTime(i.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (i *InvoiceLine) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type InvoiceLinePaymentStatus string

const (
	InvoiceLinePaymentStatusPending       InvoiceLinePaymentStatus = "pending"
	InvoiceLinePaymentStatusPaid          InvoiceLinePaymentStatus = "paid"
	InvoiceLinePaymentStatusPartiallyPaid InvoiceLinePaymentStatus = "partiallyPaid"
	InvoiceLinePaymentStatusOverdue       InvoiceLinePaymentStatus = "overdue"
	InvoiceLinePaymentStatusError         InvoiceLinePaymentStatus = "error"
)

func NewInvoiceLinePaymentStatusFromString(s string) (InvoiceLinePaymentStatus, error) {
	switch s {
	case "pending":
		return InvoiceLinePaymentStatusPending, nil
	case "paid":
		return InvoiceLinePaymentStatusPaid, nil
	case "partiallyPaid":
		return InvoiceLinePaymentStatusPartiallyPaid, nil
	case "overdue":
		return InvoiceLinePaymentStatusOverdue, nil
	case "error":
		return InvoiceLinePaymentStatusError, nil
	}
	var t InvoiceLinePaymentStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i InvoiceLinePaymentStatus) Ptr() *InvoiceLinePaymentStatus {
	return &i
}

type InvoiceLinesResponse struct {
	Data       []*InvoiceLine `json:"data" url:"data"`
	Pagination *Pagination    `json:"pagination" url:"pagination"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InvoiceLinesResponse) GetData() []*InvoiceLine {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *InvoiceLinesResponse) GetPagination() *Pagination {
	if i == nil {
		return nil
	}
	return i.Pagination
}

func (i *InvoiceLinesResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *InvoiceLinesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler InvoiceLinesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InvoiceLinesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InvoiceLinesResponse) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type InvoiceListResponse struct {
	Data       []*Invoice  `json:"data" url:"data"`
	Pagination *Pagination `json:"pagination" url:"pagination"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InvoiceListResponse) GetData() []*Invoice {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *InvoiceListResponse) GetPagination() *Pagination {
	if i == nil {
		return nil
	}
	return i.Pagination
}

func (i *InvoiceListResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *InvoiceListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler InvoiceListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InvoiceListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InvoiceListResponse) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type InvoicePaymentStatus string

const (
	InvoicePaymentStatusPending       InvoicePaymentStatus = "pending"
	InvoicePaymentStatusPaid          InvoicePaymentStatus = "paid"
	InvoicePaymentStatusPartiallyPaid InvoicePaymentStatus = "partiallyPaid"
	InvoicePaymentStatusOverdue       InvoicePaymentStatus = "overdue"
	InvoicePaymentStatusError         InvoicePaymentStatus = "error"
)

func NewInvoicePaymentStatusFromString(s string) (InvoicePaymentStatus, error) {
	switch s {
	case "pending":
		return InvoicePaymentStatusPending, nil
	case "paid":
		return InvoicePaymentStatusPaid, nil
	case "partiallyPaid":
		return InvoicePaymentStatusPartiallyPaid, nil
	case "overdue":
		return InvoicePaymentStatusOverdue, nil
	case "error":
		return InvoicePaymentStatusError, nil
	}
	var t InvoicePaymentStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i InvoicePaymentStatus) Ptr() *InvoicePaymentStatus {
	return &i
}

type InvoiceSource string

const (
	InvoiceSourceOrderBased InvoiceSource = "order_based"
	InvoiceSourceManual     InvoiceSource = "manual"
)

func NewInvoiceSourceFromString(s string) (InvoiceSource, error) {
	switch s {
	case "order_based":
		return InvoiceSourceOrderBased, nil
	case "manual":
		return InvoiceSourceManual, nil
	}
	var t InvoiceSource
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i InvoiceSource) Ptr() *InvoiceSource {
	return &i
}

type InvoiceStatus string

const (
	InvoiceStatusBuilding InvoiceStatus = "building"
	InvoiceStatusDraft    InvoiceStatus = "draft"
	InvoiceStatusPending  InvoiceStatus = "pending"
	InvoiceStatusPosted   InvoiceStatus = "posted"
	InvoiceStatusVoided   InvoiceStatus = "voided"
	InvoiceStatusCanceled InvoiceStatus = "canceled"
	InvoiceStatusError    InvoiceStatus = "error"
)

func NewInvoiceStatusFromString(s string) (InvoiceStatus, error) {
	switch s {
	case "building":
		return InvoiceStatusBuilding, nil
	case "draft":
		return InvoiceStatusDraft, nil
	case "pending":
		return InvoiceStatusPending, nil
	case "posted":
		return InvoiceStatusPosted, nil
	case "voided":
		return InvoiceStatusVoided, nil
	case "canceled":
		return InvoiceStatusCanceled, nil
	case "error":
		return InvoiceStatusError, nil
	}
	var t InvoiceStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i InvoiceStatus) Ptr() *InvoiceStatus {
	return &i
}

type InvoiceTaxStatus string

const (
	InvoiceTaxStatusNotApplicable InvoiceTaxStatus = "not_applicable"
	InvoiceTaxStatusCalculated    InvoiceTaxStatus = "calculated"
	InvoiceTaxStatusCommitted     InvoiceTaxStatus = "committed"
	InvoiceTaxStatusFailed        InvoiceTaxStatus = "failed"
	InvoiceTaxStatusVoided        InvoiceTaxStatus = "voided"
)

func NewInvoiceTaxStatusFromString(s string) (InvoiceTaxStatus, error) {
	switch s {
	case "not_applicable":
		return InvoiceTaxStatusNotApplicable, nil
	case "calculated":
		return InvoiceTaxStatusCalculated, nil
	case "committed":
		return InvoiceTaxStatusCommitted, nil
	case "failed":
		return InvoiceTaxStatusFailed, nil
	case "voided":
		return InvoiceTaxStatusVoided, nil
	}
	var t InvoiceTaxStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i InvoiceTaxStatus) Ptr() *InvoiceTaxStatus {
	return &i
}

type UpdateInvoiceRequest struct {
	ID       string                 `json:"-" url:"-"`
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"-"`
}
