// Code generated by Fern. DO NOT EDIT.

package api

type OrderCreate struct {
	CustomerId         string             `json:"customerId" url:"-"`
	CustomerExternalId *string            `json:"customerExternalId,omitempty" url:"-"`
	BillingContactId   string             `json:"billingContactId" url:"-"`
	Name               string             `json:"name" url:"-"`
	Description        *string            `json:"description,omitempty" url:"-"`
	StartDate          string             `json:"startDate" url:"-"`
	EndDate            *string            `json:"endDate,omitempty" url:"-"`
	Currency           string             `json:"currency" url:"-"`
	OrderLines         []*OrderLineCreate `json:"orderLines,omitempty" url:"-"`
}
