// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/paid-ai/paid-go/internal"
	time "time"
)

type CreatePaymentMethodRequest struct {
	// Paid customer ID to attach the payment method to.
	CustomerID *string `json:"customerId,omitempty" url:"-"`
	// Your external customer ID to attach the payment method to.
	ExternalCustomerID *string `json:"externalCustomerId,omitempty" url:"-"`
	// Confirmation token generated client-side by the payment processor's elements (e.g. a Stripe ConfirmationToken ID).
	ConfirmationToken string `json:"confirmationToken" url:"-"`
	// URL the customer is redirected to after completing any additional authentication step (e.g. 3-D Secure).
	ReturnURL *string `json:"returnUrl,omitempty" url:"-"`
	// Key-value metadata stored on the setup intent.
	Metadata map[string]string `json:"metadata,omitempty" url:"-"`
}

type DeletePaymentMethodRequest struct {
	ID string `json:"-" url:"-"`
}

type GetPaymentMethodRequest struct {
	ID string `json:"-" url:"-"`
}

type ListPaymentMethodsRequest struct {
	Limit  *int `json:"-" url:"limit,omitempty"`
	Offset *int `json:"-" url:"offset,omitempty"`
	// Filter by Paid customer ID.
	CustomerID *string `json:"-" url:"customerId,omitempty"`
	// Filter by your external customer ID.
	ExternalCustomerID *string `json:"-" url:"externalCustomerId,omitempty"`
}

type PaymentMethod struct {
	// Unique payment method identifier.
	ID string `json:"id" url:"id"`
	// The customer this payment method belongs to.
	CustomerID string `json:"customerId" url:"customerId"`
	// The payment processor's identifier for this payment method (e.g. a Stripe payment method ID).
	ExternalPaymentMethodID string `json:"externalPaymentMethodId" url:"externalPaymentMethodId"`
	// Payment method type, e.g. "card".
	Type string `json:"type" url:"type"`
	// Whether this is the customer's default payment method.
	IsDefault bool               `json:"isDefault" url:"isDefault"`
	Card      *PaymentMethodCard `json:"card,omitempty" url:"card,omitempty"`
	CreatedAt time.Time          `json:"createdAt" url:"createdAt"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaymentMethod) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PaymentMethod) GetCustomerID() string {
	if p == nil {
		return ""
	}
	return p.CustomerID
}

func (p *PaymentMethod) GetExternalPaymentMethodID() string {
	if p == nil {
		return ""
	}
	return p.ExternalPaymentMethodID
}

func (p *PaymentMethod) GetType() string {
	if p == nil {
		return ""
	}
	return p.Type
}

func (p *PaymentMethod) GetIsDefault() bool {
	if p == nil {
		return false
	}
	return p.IsDefault
}

func (p *PaymentMethod) GetCard() *PaymentMethodCard {
	if p == nil {
		return nil
	}
	return p.Card
}

func (p *PaymentMethod) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PaymentMethod) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaymentMethod) UnmarshalJSON(data []byte) error {
	type embed PaymentMethod
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PaymentMethod(unmarshaler.embed)
	p.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaymentMethod) MarshalJSON() ([]byte, error) {
	type embed PaymentMethod
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
	}{
		embed:     embed(*p),
		CreatedAt: internal.NewDateTime(p.CreatedAt),
	}
	return json.Marshal(marshaler)
}

func (p *PaymentMethod) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Card details when the payment method is a card. Null for other types or when details are unavailable.
type PaymentMethodCard struct {
	// Card brand, e.g. visa or mastercard.
	Brand string `json:"brand" url:"brand"`
	// Last four digits of the card number.
	Last4 string `json:"last4" url:"last4"`
	// Card expiration month (1-12).
	ExpMonth int `json:"expMonth" url:"expMonth"`
	// Four-digit card expiration year.
	ExpYear int `json:"expYear" url:"expYear"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaymentMethodCard) GetBrand() string {
	if p == nil {
		return ""
	}
	return p.Brand
}

func (p *PaymentMethodCard) GetLast4() string {
	if p == nil {
		return ""
	}
	return p.Last4
}

func (p *PaymentMethodCard) GetExpMonth() int {
	if p == nil {
		return 0
	}
	return p.ExpMonth
}

func (p *PaymentMethodCard) GetExpYear() int {
	if p == nil {
		return 0
	}
	return p.ExpYear
}

func (p *PaymentMethodCard) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaymentMethodCard) UnmarshalJSON(data []byte) error {
	type unmarshaler PaymentMethodCard
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaymentMethodCard(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaymentMethodCard) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PaymentMethodListResponse struct {
	Data       []*PaymentMethod `json:"data" url:"data"`
	Pagination *Pagination      `json:"pagination" url:"pagination"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaymentMethodListResponse) GetData() []*PaymentMethod {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PaymentMethodListResponse) GetPagination() *Pagination {
	if p == nil {
		return nil
	}
	return p.Pagination
}

func (p *PaymentMethodListResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaymentMethodListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PaymentMethodListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaymentMethodListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaymentMethodListResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PaymentMethodSetup struct {
	// The setup intent created with the payment processor.
	SetupIntent *PaymentMethodSetupSetupIntent `json:"setupIntent" url:"setupIntent"`
	// The payment processor's identifier for the attached payment method, when already available.
	ExternalPaymentMethodID *string `json:"externalPaymentMethodId,omitempty" url:"externalPaymentMethodId,omitempty"`
	// The customer the payment method is being attached to.
	CustomerID string `json:"customerId" url:"customerId"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaymentMethodSetup) GetSetupIntent() *PaymentMethodSetupSetupIntent {
	if p == nil {
		return nil
	}
	return p.SetupIntent
}

func (p *PaymentMethodSetup) GetExternalPaymentMethodID() *string {
	if p == nil {
		return nil
	}
	return p.ExternalPaymentMethodID
}

func (p *PaymentMethodSetup) GetCustomerID() string {
	if p == nil {
		return ""
	}
	return p.CustomerID
}

func (p *PaymentMethodSetup) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaymentMethodSetup) UnmarshalJSON(data []byte) error {
	type unmarshaler PaymentMethodSetup
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaymentMethodSetup(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaymentMethodSetup) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// The setup intent created with the payment processor.
type PaymentMethodSetupSetupIntent struct {
	// Identifier of the created setup intent.
	ID string `json:"id" url:"id"`
	// Client secret to complete any additional authentication step client-side. Handle it like a credential.
	ClientSecret *string `json:"clientSecret,omitempty" url:"clientSecret,omitempty"`
	// Setup intent status, e.g. succeeded or requires_action.
	Status string `json:"status" url:"status"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaymentMethodSetupSetupIntent) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PaymentMethodSetupSetupIntent) GetClientSecret() *string {
	if p == nil {
		return nil
	}
	return p.ClientSecret
}

func (p *PaymentMethodSetupSetupIntent) GetStatus() string {
	if p == nil {
		return ""
	}
	return p.Status
}

func (p *PaymentMethodSetupSetupIntent) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaymentMethodSetupSetupIntent) UnmarshalJSON(data []byte) error {
	type unmarshaler PaymentMethodSetupSetupIntent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaymentMethodSetupSetupIntent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaymentMethodSetupSetupIntent) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type UpdateDefaultPaymentMethodRequest struct {
	ID string `json:"-" url:"-"`
}
