// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/paid-ai/paid-go/internal"
	time "time"
)

type CreatePaymentRequest struct {
	// Paid customer ID the payment belongs to.
	CustomerID *string `json:"customerId,omitempty" url:"-"`
	// Your external customer ID the payment belongs to.
	ExternalCustomerID *string `json:"externalCustomerId,omitempty" url:"-"`
	// Payment amount in cents (minor currency units).
	Amount int `json:"amount" url:"-"`
	// Three-letter ISO currency code.
	Currency string `json:"currency" url:"-"`
	// When the payment was made (ISO 8601). Defaults to the current time.
	PaymentDate *time.Time           `json:"paymentDate,omitempty" url:"-"`
	PaymentType PaymentType          `json:"paymentType" url:"-"`
	Status      *PaymentCreateStatus `json:"status,omitempty" url:"-"`
	// Key-value metadata stored on the payment.
	Metadata map[string]interface{} `json:"metadata,omitempty" url:"-"`
}

func (c *CreatePaymentRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePaymentRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreatePaymentRequest(body)
	return nil
}

func (c *CreatePaymentRequest) MarshalJSON() ([]byte, error) {
	type embed CreatePaymentRequest
	var marshaler = struct {
		embed
		PaymentDate *internal.DateTime `json:"paymentDate,omitempty"`
	}{
		embed:       embed(*c),
		PaymentDate: internal.NewOptionalDateTime(c.PaymentDate),
	}
	return json.Marshal(marshaler)
}

type GetPaymentRequest struct {
	ID string `json:"-" url:"-"`
}

type ListPaymentsRequest struct {
	Limit  *int `json:"-" url:"limit,omitempty"`
	Offset *int `json:"-" url:"offset,omitempty"`
	// Filter by Paid customer ID.
	CustomerID *string `json:"-" url:"customerId,omitempty"`
	// Filter by your external customer ID.
	ExternalCustomerID *string `json:"-" url:"externalCustomerId,omitempty"`
	// Filter by payment status.
	Status *ListPaymentsRequestStatus `json:"-" url:"status,omitempty"`
}

type Payment struct {
	// Unique payment identifier.
	ID string `json:"id" url:"id"`
	// Sequential payment number within your organization (shown as "PAY-0001").
	Number int `json:"number" url:"number"`
	// The customer this payment belongs to.
	CustomerID string `json:"customerId" url:"customerId"`
	// The invoice this payment was collected for, when created by an automatic charge. Null for manually recorded payments.
	InvoiceID *string `json:"invoiceId,omitempty" url:"invoiceId,omitempty"`
	// The order this payment relates to, when known.
	OrderID *string `json:"orderId,omitempty" url:"orderId,omitempty"`
	// Payment amount in cents (minor currency units).
	Amount int `json:"amount" url:"amount"`
	// Portion of the amount already allocated to invoice lines, in cents.
	AllocatedAmount int `json:"allocatedAmount" url:"allocatedAmount"`
	// Unallocated remainder of the payment, in cents.
	Balance int `json:"balance" url:"balance"`
	// Three-letter ISO currency code.
	Currency string `json:"currency" url:"currency"`
	// When the payment was made.
	PaymentDate time.Time `json:"paymentDate" url:"paymentDate"`
	// How the payment was made, e.g. creditCard, bankTransfer, ach, cash, or check.
	PaymentType string `json:"paymentType" url:"paymentType"`
	// Payment status: draft, posted, processing, requiresAction, failed, or canceled.
	Status string `json:"status" url:"status"`
	// Key-value metadata stored on the payment.
	Metadata  map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	CreatedAt time.Time              `json:"createdAt" url:"createdAt"`
	UpdatedAt time.Time              `json:"updatedAt" url:"updatedAt"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *Payment) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *Payment) GetNumber() int {
	if p == nil {
		return 0
	}
	return p.Number
}

func (p *Payment) GetCustomerID() string {
	if p == nil {
		return ""
	}
	return p.CustomerID
}

func (p *Payment) GetInvoiceID() *string {
	if p == nil {
		return nil
	}
	return p.InvoiceID
}

func (p *Payment) GetOrderID() *string {
	if p == nil {
		return nil
	}
	return p.OrderID
}

func (p *Payment) GetAmount() int {
	if p == nil {
		return 0
	}
	return p.Amount
}

func (p *Payment) GetAllocatedAmount() int {
	if p == nil {
		return 0
	}
	return p.AllocatedAmount
}

func (p *Payment) GetBalance() int {
	if p == nil {
		return 0
	}
	return p.Balance
}

func (p *Payment) GetCurrency() string {
	if p == nil {
		return ""
	}
	return p.Currency
}

func (p *Payment) GetPaymentDate() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.PaymentDate
}

func (p *Payment) GetPaymentType() string {
	if p == nil {
		return ""
	}
	return p.PaymentType
}

func (p *Payment) GetStatus() string {
	if p == nil {
		return ""
	}
	return p.Status
}

func (p *Payment) GetMetadata() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.Metadata
}

func (p *Payment) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *Payment) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}

func (p *Payment) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *Payment) UnmarshalJSON(data []byte) error {
	type embed Payment
	var unmarshaler = struct {
		embed
		PaymentDate *internal.DateTime `json:"paymentDate"`
		CreatedAt   *internal.DateTime `json:"createdAt"`
		UpdatedAt   *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = Payment(unmarshaler.embed)
	p.PaymentDate = unmarshaler.PaymentDate.Time()
	p.CreatedAt = unmarshaler.CreatedAt.Time()
	p.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *Payment) MarshalJSON() ([]byte, error) {
	type embed Payment
	var marshaler = struct {
		embed
		PaymentDate *internal.DateTime `json:"paymentDate"`
		CreatedAt   *internal.DateTime `json:"createdAt"`
		UpdatedAt   *internal.DateTime `json:"updatedAt"`
	}{
		embed:       embed(*p),
		PaymentDate: internal.NewDateTime(p.PaymentDate),
		CreatedAt:   internal.NewDateTime(p.CreatedAt),
		UpdatedAt:   internal.NewDateTime(p.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (p *Payment) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Initial status. Use draft to keep the payment editable, posted to record it as received. Defaults to posted.
type PaymentCreateStatus string

const (
	PaymentCreateStatusDraft  PaymentCreateStatus = "draft"
	PaymentCreateStatusPosted PaymentCreateStatus = "posted"
)

func NewPaymentCreateStatusFromString(s string) (PaymentCreateStatus, error) {
	switch s {
	case "draft":
		return PaymentCreateStatusDraft, nil
	case "posted":
		return PaymentCreateStatusPosted, nil
	}
	var t PaymentCreateStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PaymentCreateStatus) Ptr() *PaymentCreateStatus {
	return &p
}

type PaymentListResponse struct {
	Data       []*Payment  `json:"data" url:"data"`
	Pagination *Pagination `json:"pagination" url:"pagination"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaymentListResponse) GetData() []*Payment {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PaymentListResponse) GetPagination() *Pagination {
	if p == nil {
		return nil
	}
	return p.Pagination
}

func (p *PaymentListResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaymentListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PaymentListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaymentListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaymentListResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// How the payment was made.
type PaymentType string

const (
	PaymentTypeCreditCard   PaymentType = "creditCard"
	PaymentTypeBankTransfer PaymentType = "bankTransfer"
	PaymentTypeAch          PaymentType = "ach"
	PaymentTypeCash         PaymentType = "cash"
	PaymentTypeCheck        PaymentType = "check"
)

func NewPaymentTypeFromString(s string) (PaymentType, error) {
	switch s {
	case "creditCard":
		return PaymentTypeCreditCard, nil
	case "bankTransfer":
		return PaymentTypeBankTransfer, nil
	case "ach":
		return PaymentTypeAch, nil
	case "cash":
		return PaymentTypeCash, nil
	case "check":
		return PaymentTypeCheck, nil
	}
	var t PaymentType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PaymentType) Ptr() *PaymentType {
	return &p
}

type ListPaymentsRequestStatus string

const (
	ListPaymentsRequestStatusDraft          ListPaymentsRequestStatus = "draft"
	ListPaymentsRequestStatusPosted         ListPaymentsRequestStatus = "posted"
	ListPaymentsRequestStatusProcessing     ListPaymentsRequestStatus = "processing"
	ListPaymentsRequestStatusRequiresAction ListPaymentsRequestStatus = "requiresAction"
	ListPaymentsRequestStatusFailed         ListPaymentsRequestStatus = "failed"
	ListPaymentsRequestStatusCanceled       ListPaymentsRequestStatus = "canceled"
)

func NewListPaymentsRequestStatusFromString(s string) (ListPaymentsRequestStatus, error) {
	switch s {
	case "draft":
		return ListPaymentsRequestStatusDraft, nil
	case "posted":
		return ListPaymentsRequestStatusPosted, nil
	case "processing":
		return ListPaymentsRequestStatusProcessing, nil
	case "requiresAction":
		return ListPaymentsRequestStatusRequiresAction, nil
	case "failed":
		return ListPaymentsRequestStatusFailed, nil
	case "canceled":
		return ListPaymentsRequestStatusCanceled, nil
	}
	var t ListPaymentsRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListPaymentsRequestStatus) Ptr() *ListPaymentsRequestStatus {
	return &l
}
