// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/paid-ai/paid-go/internal"
	time "time"
)

type CreatePlanRequest struct {
	// Paid product ID, for example `prod_abc123`
	ProductID string  `json:"productId" url:"-"`
	Name      *string `json:"name,omitempty" url:"-"`
	// Your stable identifier for this plan
	ExternalID          *string               `json:"externalId,omitempty" url:"-"`
	SupportedCurrencies []string              `json:"supportedCurrencies,omitempty" url:"-"`
	IsDefault           *bool                 `json:"isDefault,omitempty" url:"-"`
	Attributes          []*PlanAttributeInput `json:"attributes,omitempty" url:"-"`
}

type GetPlanByExternalIDRequest struct {
	ExternalID string `json:"-" url:"-"`
}

type GetPlanByIDRequest struct {
	ID string `json:"-" url:"-"`
}

type ListPlansRequest struct {
	Limit             *int    `json:"-" url:"limit,omitempty"`
	Offset            *int    `json:"-" url:"offset,omitempty"`
	ProductID         *string `json:"-" url:"productId,omitempty"`
	ExternalProductID *string `json:"-" url:"externalProductId,omitempty"`
	// Whether to include archived plans in the response. Defaults to true.
	IncludeArchived *bool `json:"-" url:"includeArchived,omitempty"`
}

type Plan struct {
	ID                  string           `json:"id" url:"id"`
	ProductID           string           `json:"productId" url:"productId"`
	Name                *string          `json:"name,omitempty" url:"name,omitempty"`
	ExternalID          *string          `json:"externalId,omitempty" url:"externalId,omitempty"`
	SupportedCurrencies []string         `json:"supportedCurrencies" url:"supportedCurrencies"`
	IsDefault           bool             `json:"isDefault" url:"isDefault"`
	Status              PlanStatus       `json:"status" url:"status"`
	UpgradePathOrder    *float64         `json:"upgradePathOrder,omitempty" url:"upgradePathOrder,omitempty"`
	ArchivedAt          *time.Time       `json:"archivedAt,omitempty" url:"archivedAt,omitempty"`
	CreatedAt           time.Time        `json:"createdAt" url:"createdAt"`
	UpdatedAt           time.Time        `json:"updatedAt" url:"updatedAt"`
	Attributes          []*PlanAttribute `json:"attributes" url:"attributes"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *Plan) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *Plan) GetProductID() string {
	if p == nil {
		return ""
	}
	return p.ProductID
}

func (p *Plan) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *Plan) GetExternalID() *string {
	if p == nil {
		return nil
	}
	return p.ExternalID
}

func (p *Plan) GetSupportedCurrencies() []string {
	if p == nil {
		return nil
	}
	return p.SupportedCurrencies
}

func (p *Plan) GetIsDefault() bool {
	if p == nil {
		return false
	}
	return p.IsDefault
}

func (p *Plan) GetStatus() PlanStatus {
	if p == nil {
		return ""
	}
	return p.Status
}

func (p *Plan) GetUpgradePathOrder() *float64 {
	if p == nil {
		return nil
	}
	return p.UpgradePathOrder
}

func (p *Plan) GetArchivedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.ArchivedAt
}

func (p *Plan) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *Plan) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}

func (p *Plan) GetAttributes() []*PlanAttribute {
	if p == nil {
		return nil
	}
	return p.Attributes
}

func (p *Plan) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *Plan) UnmarshalJSON(data []byte) error {
	type embed Plan
	var unmarshaler = struct {
		embed
		ArchivedAt *internal.DateTime `json:"archivedAt,omitempty"`
		CreatedAt  *internal.DateTime `json:"createdAt"`
		UpdatedAt  *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = Plan(unmarshaler.embed)
	p.ArchivedAt = unmarshaler.ArchivedAt.TimePtr()
	p.CreatedAt = unmarshaler.CreatedAt.Time()
	p.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *Plan) MarshalJSON() ([]byte, error) {
	type embed Plan
	var marshaler = struct {
		embed
		ArchivedAt *internal.DateTime `json:"archivedAt,omitempty"`
		CreatedAt  *internal.DateTime `json:"createdAt"`
		UpdatedAt  *internal.DateTime `json:"updatedAt"`
	}{
		embed:      embed(*p),
		ArchivedAt: internal.NewOptionalDateTime(p.ArchivedAt),
		CreatedAt:  internal.NewDateTime(p.CreatedAt),
		UpdatedAt:  internal.NewDateTime(p.UpdatedAt),
	}
	return json.Marshal(marshaler)
}

func (p *Plan) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PlanAttribute struct {
	ProductAttributeID string               `json:"productAttributeId" url:"productAttributeId"`
	Name               string               `json:"name" url:"name"`
	Active             bool                 `json:"active" url:"active"`
	Pricing            *PlanPricing         `json:"pricing,omitempty" url:"pricing,omitempty"`
	CreditBenefits     []*PlanCreditBenefit `json:"creditBenefits" url:"creditBenefits"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PlanAttribute) GetProductAttributeID() string {
	if p == nil {
		return ""
	}
	return p.ProductAttributeID
}

func (p *PlanAttribute) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PlanAttribute) GetActive() bool {
	if p == nil {
		return false
	}
	return p.Active
}

func (p *PlanAttribute) GetPricing() *PlanPricing {
	if p == nil {
		return nil
	}
	return p.Pricing
}

func (p *PlanAttribute) GetCreditBenefits() []*PlanCreditBenefit {
	if p == nil {
		return nil
	}
	return p.CreditBenefits
}

func (p *PlanAttribute) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PlanAttribute) UnmarshalJSON(data []byte) error {
	type unmarshaler PlanAttribute
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PlanAttribute(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PlanAttribute) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PlanAttributeInput struct {
	// Product attribute ID to override in this plan
	ProductAttributeID string                       `json:"productAttributeId" url:"productAttributeId"`
	Pricing            *ProductPricingInput         `json:"pricing" url:"pricing"`
	CreditBenefits     []*ProductCreditBenefitInput `json:"creditBenefits,omitempty" url:"creditBenefits,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PlanAttributeInput) GetProductAttributeID() string {
	if p == nil {
		return ""
	}
	return p.ProductAttributeID
}

func (p *PlanAttributeInput) GetPricing() *ProductPricingInput {
	if p == nil {
		return nil
	}
	return p.Pricing
}

func (p *PlanAttributeInput) GetCreditBenefits() []*ProductCreditBenefitInput {
	if p == nil {
		return nil
	}
	return p.CreditBenefits
}

func (p *PlanAttributeInput) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PlanAttributeInput) UnmarshalJSON(data []byte) error {
	type unmarshaler PlanAttributeInput
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PlanAttributeInput(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PlanAttributeInput) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PlanCreditBenefit struct {
	ID                   string                                 `json:"id" url:"id"`
	CreditsCurrencyID    *string                                `json:"creditsCurrencyId,omitempty" url:"creditsCurrencyId,omitempty"`
	Recipient            *PlanCreditBenefitRecipient            `json:"recipient,omitempty" url:"recipient,omitempty"`
	Amount               float64                                `json:"amount" url:"amount"`
	RolloverAmount       *float64                               `json:"rolloverAmount,omitempty" url:"rolloverAmount,omitempty"`
	RolloverDuration     *float64                               `json:"rolloverDuration,omitempty" url:"rolloverDuration,omitempty"`
	RolloverDurationUnit *PlanCreditBenefitRolloverDurationUnit `json:"rolloverDurationUnit,omitempty" url:"rolloverDurationUnit,omitempty"`
	AllocationCadence    *PlanCreditBenefitAllocationCadence    `json:"allocationCadence,omitempty" url:"allocationCadence,omitempty"`
	CreditGrantTiming    *PlanCreditBenefitCreditGrantTiming    `json:"creditGrantTiming,omitempty" url:"creditGrantTiming,omitempty"`
	IsInfiniteTotal      *bool                                  `json:"isInfiniteTotal,omitempty" url:"isInfiniteTotal,omitempty"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (p *PlanCreditBenefit) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PlanCreditBenefit) GetCreditsCurrencyID() *string {
	if p == nil {
		return nil
	}
	return p.CreditsCurrencyID
}

func (p *PlanCreditBenefit) GetRecipient() *PlanCreditBenefitRecipient {
	if p == nil {
		return nil
	}
	return p.Recipient
}

func (p *PlanCreditBenefit) GetAmount() float64 {
	if p == nil {
		return 0
	}
	return p.Amount
}

func (p *PlanCreditBenefit) GetRolloverAmount() *float64 {
	if p == nil {
		return nil
	}
	return p.RolloverAmount
}

func (p *PlanCreditBenefit) GetRolloverDuration() *float64 {
	if p == nil {
		return nil
	}
	return p.RolloverDuration
}

func (p *PlanCreditBenefit) GetRolloverDurationUnit() *PlanCreditBenefitRolloverDurationUnit {
	if p == nil {
		return nil
	}
	return p.RolloverDurationUnit
}

func (p *PlanCreditBenefit) GetAllocationCadence() *PlanCreditBenefitAllocationCadence {
	if p == nil {
		return nil
	}
	return p.AllocationCadence
}

func (p *PlanCreditBenefit) GetCreditGrantTiming() *PlanCreditBenefitCreditGrantTiming {
	if p == nil {
		return nil
	}
	return p.CreditGrantTiming
}

func (p *PlanCreditBenefit) GetIsInfiniteTotal() *bool {
	if p == nil {
		return nil
	}
	return p.IsInfiniteTotal
}

func (p *PlanCreditBenefit) GetExtraProperties() map[string]interface{} {
	return p.ExtraProperties
}

func (p *PlanCreditBenefit) UnmarshalJSON(data []byte) error {
	type embed PlanCreditBenefit
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PlanCreditBenefit(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.ExtraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PlanCreditBenefit) MarshalJSON() ([]byte, error) {
	type embed PlanCreditBenefit
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	return internal.MarshalJSONWithExtraProperties(marshaler, p.ExtraProperties)
}

func (p *PlanCreditBenefit) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PlanCreditBenefitAllocationCadence string

const (
	PlanCreditBenefitAllocationCadenceUpfront PlanCreditBenefitAllocationCadence = "upfront"
	PlanCreditBenefitAllocationCadenceMonthly PlanCreditBenefitAllocationCadence = "monthly"
)

func NewPlanCreditBenefitAllocationCadenceFromString(s string) (PlanCreditBenefitAllocationCadence, error) {
	switch s {
	case "upfront":
		return PlanCreditBenefitAllocationCadenceUpfront, nil
	case "monthly":
		return PlanCreditBenefitAllocationCadenceMonthly, nil
	}
	var t PlanCreditBenefitAllocationCadence
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PlanCreditBenefitAllocationCadence) Ptr() *PlanCreditBenefitAllocationCadence {
	return &p
}

type PlanCreditBenefitCreditGrantTiming string

const (
	PlanCreditBenefitCreditGrantTimingOnPayment         PlanCreditBenefitCreditGrantTiming = "on_payment"
	PlanCreditBenefitCreditGrantTimingOnInvoicePosted   PlanCreditBenefitCreditGrantTiming = "on_invoice_posted"
	PlanCreditBenefitCreditGrantTimingOnOrderActivation PlanCreditBenefitCreditGrantTiming = "on_order_activation"
)

func NewPlanCreditBenefitCreditGrantTimingFromString(s string) (PlanCreditBenefitCreditGrantTiming, error) {
	switch s {
	case "on_payment":
		return PlanCreditBenefitCreditGrantTimingOnPayment, nil
	case "on_invoice_posted":
		return PlanCreditBenefitCreditGrantTimingOnInvoicePosted, nil
	case "on_order_activation":
		return PlanCreditBenefitCreditGrantTimingOnOrderActivation, nil
	}
	var t PlanCreditBenefitCreditGrantTiming
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PlanCreditBenefitCreditGrantTiming) Ptr() *PlanCreditBenefitCreditGrantTiming {
	return &p
}

type PlanCreditBenefitRecipient string

const (
	PlanCreditBenefitRecipientOrganization PlanCreditBenefitRecipient = "organization"
	PlanCreditBenefitRecipientSeat         PlanCreditBenefitRecipient = "seat"
)

func NewPlanCreditBenefitRecipientFromString(s string) (PlanCreditBenefitRecipient, error) {
	switch s {
	case "organization":
		return PlanCreditBenefitRecipientOrganization, nil
	case "seat":
		return PlanCreditBenefitRecipientSeat, nil
	}
	var t PlanCreditBenefitRecipient
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PlanCreditBenefitRecipient) Ptr() *PlanCreditBenefitRecipient {
	return &p
}

type PlanCreditBenefitRolloverDurationUnit string

const (
	PlanCreditBenefitRolloverDurationUnitDays   PlanCreditBenefitRolloverDurationUnit = "days"
	PlanCreditBenefitRolloverDurationUnitMonths PlanCreditBenefitRolloverDurationUnit = "months"
)

func NewPlanCreditBenefitRolloverDurationUnitFromString(s string) (PlanCreditBenefitRolloverDurationUnit, error) {
	switch s {
	case "days":
		return PlanCreditBenefitRolloverDurationUnitDays, nil
	case "months":
		return PlanCreditBenefitRolloverDurationUnitMonths, nil
	}
	var t PlanCreditBenefitRolloverDurationUnit
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PlanCreditBenefitRolloverDurationUnit) Ptr() *PlanCreditBenefitRolloverDurationUnit {
	return &p
}

type PlanListResponse struct {
	Data       []*Plan     `json:"data" url:"data"`
	Pagination *Pagination `json:"pagination" url:"pagination"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PlanListResponse) GetData() []*Plan {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PlanListResponse) GetPagination() *Pagination {
	if p == nil {
		return nil
	}
	return p.Pagination
}

func (p *PlanListResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PlanListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PlanListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PlanListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PlanListResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Pricing configuration for a plan attribute. Money amounts are expressed in cents.
type PlanPricing struct {
	PricingType  *PlanPricingPricingType  `json:"pricingType,omitempty" url:"pricingType,omitempty"`
	ChargeType   string                   `json:"chargeType" url:"chargeType"`
	PricingModel string                   `json:"pricingModel" url:"pricingModel"`
	PricePoints  []map[string]interface{} `json:"pricePoints" url:"pricePoints"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (p *PlanPricing) GetPricingType() *PlanPricingPricingType {
	if p == nil {
		return nil
	}
	return p.PricingType
}

func (p *PlanPricing) GetChargeType() string {
	if p == nil {
		return ""
	}
	return p.ChargeType
}

func (p *PlanPricing) GetPricingModel() string {
	if p == nil {
		return ""
	}
	return p.PricingModel
}

func (p *PlanPricing) GetPricePoints() []map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.PricePoints
}

func (p *PlanPricing) GetExtraProperties() map[string]interface{} {
	return p.ExtraProperties
}

func (p *PlanPricing) UnmarshalJSON(data []byte) error {
	type embed PlanPricing
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PlanPricing(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.ExtraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PlanPricing) MarshalJSON() ([]byte, error) {
	type embed PlanPricing
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	return internal.MarshalJSONWithExtraProperties(marshaler, p.ExtraProperties)
}

func (p *PlanPricing) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PlanPricingPricingType string

const (
	PlanPricingPricingTypeRecurringPerUnit             PlanPricingPricingType = "RecurringPerUnit"
	PlanPricingPricingTypeRecurringGraduated           PlanPricingPricingType = "RecurringGraduated"
	PlanPricingPricingTypeRecurringVolume              PlanPricingPricingType = "RecurringVolume"
	PlanPricingPricingTypeRecurringPercentOfTotal      PlanPricingPricingType = "RecurringPercentOfTotal"
	PlanPricingPricingTypeUsagePerUnit                 PlanPricingPricingType = "UsagePerUnit"
	PlanPricingPricingTypeUsageGraduated               PlanPricingPricingType = "UsageGraduated"
	PlanPricingPricingTypeUsageVolume                  PlanPricingPricingType = "UsageVolume"
	PlanPricingPricingTypeUsagePrepaidCredits          PlanPricingPricingType = "UsagePrepaidCredits"
	PlanPricingPricingTypeUsageBracketedPrepaidCredits PlanPricingPricingType = "UsageBracketedPrepaidCredits"
	PlanPricingPricingTypeUsageCostPlus                PlanPricingPricingType = "UsageCostPlus"
	PlanPricingPricingTypeOneTimePerUnit               PlanPricingPricingType = "OneTimePerUnit"
	PlanPricingPricingTypeSeatBasedPerUnit             PlanPricingPricingType = "SeatBasedPerUnit"
	PlanPricingPricingTypeSeatBasedGraduated           PlanPricingPricingType = "SeatBasedGraduated"
	PlanPricingPricingTypeSeatBasedVolume              PlanPricingPricingType = "SeatBasedVolume"
	PlanPricingPricingTypeSeatBasedPrepaidCredits      PlanPricingPricingType = "SeatBasedPrepaidCredits"
)

func NewPlanPricingPricingTypeFromString(s string) (PlanPricingPricingType, error) {
	switch s {
	case "RecurringPerUnit":
		return PlanPricingPricingTypeRecurringPerUnit, nil
	case "RecurringGraduated":
		return PlanPricingPricingTypeRecurringGraduated, nil
	case "RecurringVolume":
		return PlanPricingPricingTypeRecurringVolume, nil
	case "RecurringPercentOfTotal":
		return PlanPricingPricingTypeRecurringPercentOfTotal, nil
	case "UsagePerUnit":
		return PlanPricingPricingTypeUsagePerUnit, nil
	case "UsageGraduated":
		return PlanPricingPricingTypeUsageGraduated, nil
	case "UsageVolume":
		return PlanPricingPricingTypeUsageVolume, nil
	case "UsagePrepaidCredits":
		return PlanPricingPricingTypeUsagePrepaidCredits, nil
	case "UsageBracketedPrepaidCredits":
		return PlanPricingPricingTypeUsageBracketedPrepaidCredits, nil
	case "UsageCostPlus":
		return PlanPricingPricingTypeUsageCostPlus, nil
	case "OneTimePerUnit":
		return PlanPricingPricingTypeOneTimePerUnit, nil
	case "SeatBasedPerUnit":
		return PlanPricingPricingTypeSeatBasedPerUnit, nil
	case "SeatBasedGraduated":
		return PlanPricingPricingTypeSeatBasedGraduated, nil
	case "SeatBasedVolume":
		return PlanPricingPricingTypeSeatBasedVolume, nil
	case "SeatBasedPrepaidCredits":
		return PlanPricingPricingTypeSeatBasedPrepaidCredits, nil
	}
	var t PlanPricingPricingType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PlanPricingPricingType) Ptr() *PlanPricingPricingType {
	return &p
}

type PlanStatus string

const (
	PlanStatusActive   PlanStatus = "active"
	PlanStatusArchived PlanStatus = "archived"
)

func NewPlanStatusFromString(s string) (PlanStatus, error) {
	switch s {
	case "active":
		return PlanStatusActive, nil
	case "archived":
		return PlanStatusArchived, nil
	}
	var t PlanStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PlanStatus) Ptr() *PlanStatus {
	return &p
}

type PlanUpgradePathGroup struct {
	Frequency *string  `json:"frequency,omitempty" url:"frequency,omitempty"`
	PlanIDs   []string `json:"planIds" url:"planIds"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PlanUpgradePathGroup) GetFrequency() *string {
	if p == nil {
		return nil
	}
	return p.Frequency
}

func (p *PlanUpgradePathGroup) GetPlanIDs() []string {
	if p == nil {
		return nil
	}
	return p.PlanIDs
}

func (p *PlanUpgradePathGroup) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PlanUpgradePathGroup) UnmarshalJSON(data []byte) error {
	type unmarshaler PlanUpgradePathGroup
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PlanUpgradePathGroup(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PlanUpgradePathGroup) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PlanUpgradePathResponse struct {
	Data []*Plan `json:"data" url:"data"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PlanUpgradePathResponse) GetData() []*Plan {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PlanUpgradePathResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PlanUpgradePathResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PlanUpgradePathResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PlanUpgradePathResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PlanUpgradePathResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type UpdatePlanRequest struct {
	Name                *string  `json:"name,omitempty" url:"name,omitempty"`
	ExternalID          *string  `json:"externalId,omitempty" url:"externalId,omitempty"`
	SupportedCurrencies []string `json:"supportedCurrencies,omitempty" url:"supportedCurrencies,omitempty"`
	IsDefault           *bool    `json:"isDefault,omitempty" url:"isDefault,omitempty"`
	// Set to `archived` to archive this plan, or `active` to restore it.
	Status     *UpdatePlanRequestStatus `json:"status,omitempty" url:"status,omitempty"`
	Attributes []*PlanAttributeInput    `json:"attributes,omitempty" url:"attributes,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePlanRequest) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdatePlanRequest) GetExternalID() *string {
	if u == nil {
		return nil
	}
	return u.ExternalID
}

func (u *UpdatePlanRequest) GetSupportedCurrencies() []string {
	if u == nil {
		return nil
	}
	return u.SupportedCurrencies
}

func (u *UpdatePlanRequest) GetIsDefault() *bool {
	if u == nil {
		return nil
	}
	return u.IsDefault
}

func (u *UpdatePlanRequest) GetStatus() *UpdatePlanRequestStatus {
	if u == nil {
		return nil
	}
	return u.Status
}

func (u *UpdatePlanRequest) GetAttributes() []*PlanAttributeInput {
	if u == nil {
		return nil
	}
	return u.Attributes
}

func (u *UpdatePlanRequest) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdatePlanRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePlanRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePlanRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePlanRequest) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Set to `archived` to archive this plan, or `active` to restore it.
type UpdatePlanRequestStatus string

const (
	UpdatePlanRequestStatusActive   UpdatePlanRequestStatus = "active"
	UpdatePlanRequestStatusArchived UpdatePlanRequestStatus = "archived"
)

func NewUpdatePlanRequestStatusFromString(s string) (UpdatePlanRequestStatus, error) {
	switch s {
	case "active":
		return UpdatePlanRequestStatusActive, nil
	case "archived":
		return UpdatePlanRequestStatusArchived, nil
	}
	var t UpdatePlanRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdatePlanRequestStatus) Ptr() *UpdatePlanRequestStatus {
	return &u
}

type UpdatePlanByExternalIDRequest struct {
	ExternalID string             `json:"-" url:"-"`
	Body       *UpdatePlanRequest `json:"-" url:"-"`
}

func (u *UpdatePlanByExternalIDRequest) UnmarshalJSON(data []byte) error {
	body := new(UpdatePlanRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.Body = body
	return nil
}

func (u *UpdatePlanByExternalIDRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

type UpdatePlanByIDRequest struct {
	ID   string             `json:"-" url:"-"`
	Body *UpdatePlanRequest `json:"-" url:"-"`
}

func (u *UpdatePlanByIDRequest) UnmarshalJSON(data []byte) error {
	body := new(UpdatePlanRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.Body = body
	return nil
}

func (u *UpdatePlanByIDRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

type UpdatePlanUpgradePathRequest struct {
	// Paid product ID, for example `prod_abc123`
	ProductID string                  `json:"productId" url:"-"`
	Groups    []*PlanUpgradePathGroup `json:"groups,omitempty" url:"-"`
}
