// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "sdk/internal"
	time "time"
)

type GetTracesRequest struct {
	// Maximum number of traces to return (1-1000)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Number of traces to skip for pagination
	Offset *int `json:"-" url:"offset,omitempty"`
	// Filter traces starting from this time (ISO 8601 format)
	StartTime *time.Time `json:"-" url:"startTime,omitempty"`
	// Filter traces up to this time (ISO 8601 format)
	EndTime *time.Time `json:"-" url:"endTime,omitempty"`
	// Filter traces by external customer ID
	ExternalCustomerId *string `json:"-" url:"externalCustomerId,omitempty"`
	// Filter traces by external agent ID
	ExternalAgentId *string `json:"-" url:"externalAgentId,omitempty"`
	// Filter traces by metadata fields. Must be a valid JSON object (e.g., {"key1":"value1","key2":"value2"}). All specified fields must match (AND logic).
	Metadata *string `json:"-" url:"metadata,omitempty"`
}

// A single cost trace record with customer and product info
type Trace struct {
	// The name/type of the operation (e.g., "trace.openai.agents.on_agent")
	Name string `json:"name" url:"name"`
	// The vendor/provider (e.g., "openai", "anthropic", "mistral")
	Vendor string `json:"vendor" url:"vendor"`
	// The model used for the operation (e.g., "gpt-4o-mini", "claude-3-sonnet")
	Model string      `json:"model" url:"model"`
	Cost  *CostAmount `json:"cost" url:"cost"`
	// Unix timestamp in nanoseconds when the operation started
	StartTimeUnixNano string `json:"startTimeUnixNano" url:"startTimeUnixNano"`
	// Unix timestamp in nanoseconds when the operation completed
	EndTimeUnixNano string `json:"endTimeUnixNano" url:"endTimeUnixNano"`
	// Additional metadata about the trace (e.g., tokens, etc.)
	Attributes map[string]interface{} `json:"attributes" url:"attributes"`
	// The internal customer ID associated with this trace
	CustomerId *string `json:"customerId,omitempty" url:"customerId,omitempty"`
	// The product/agent ID associated with this trace (optional)
	ProductId *string `json:"productId,omitempty" url:"productId,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *Trace) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *Trace) GetVendor() string {
	if t == nil {
		return ""
	}
	return t.Vendor
}

func (t *Trace) GetModel() string {
	if t == nil {
		return ""
	}
	return t.Model
}

func (t *Trace) GetCost() *CostAmount {
	if t == nil {
		return nil
	}
	return t.Cost
}

func (t *Trace) GetStartTimeUnixNano() string {
	if t == nil {
		return ""
	}
	return t.StartTimeUnixNano
}

func (t *Trace) GetEndTimeUnixNano() string {
	if t == nil {
		return ""
	}
	return t.EndTimeUnixNano
}

func (t *Trace) GetAttributes() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.Attributes
}

func (t *Trace) GetCustomerId() *string {
	if t == nil {
		return nil
	}
	return t.CustomerId
}

func (t *Trace) GetProductId() *string {
	if t == nil {
		return nil
	}
	return t.ProductId
}

func (t *Trace) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *Trace) UnmarshalJSON(data []byte) error {
	type unmarshaler Trace
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = Trace(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *Trace) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Response containing cost traces and pagination metadata
type TracesResponse struct {
	Traces []*Trace        `json:"traces" url:"traces"`
	Meta   *PaginationMeta `json:"meta" url:"meta"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TracesResponse) GetTraces() []*Trace {
	if t == nil {
		return nil
	}
	return t.Traces
}

func (t *TracesResponse) GetMeta() *PaginationMeta {
	if t == nil {
		return nil
	}
	return t.Meta
}

func (t *TracesResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TracesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TracesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TracesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TracesResponse) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
