// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/paid-ai/paid-go/internal"
	time "time"
)

type Address struct {
	Line1   string  `json:"line1" url:"line1"`
	Line2   *string `json:"line2,omitempty" url:"line2,omitempty"`
	City    string  `json:"city" url:"city"`
	State   string  `json:"state" url:"state"`
	ZipCode string  `json:"zipCode" url:"zipCode"`
	Country string  `json:"country" url:"country"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *Address) GetLine1() string {
	if a == nil {
		return ""
	}
	return a.Line1
}

func (a *Address) GetLine2() *string {
	if a == nil {
		return nil
	}
	return a.Line2
}

func (a *Address) GetCity() string {
	if a == nil {
		return ""
	}
	return a.City
}

func (a *Address) GetState() string {
	if a == nil {
		return ""
	}
	return a.State
}

func (a *Address) GetZipCode() string {
	if a == nil {
		return ""
	}
	return a.ZipCode
}

func (a *Address) GetCountry() string {
	if a == nil {
		return ""
	}
	return a.Country
}

func (a *Address) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *Address) UnmarshalJSON(data []byte) error {
	type unmarshaler Address
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = Address(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *Address) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type Agent struct {
	Id              string            `json:"id" url:"id"`
	ExternalId      *string           `json:"externalId,omitempty" url:"externalId,omitempty"`
	OrganizationId  string            `json:"organizationId" url:"organizationId"`
	Name            string            `json:"name" url:"name"`
	Description     *string           `json:"description,omitempty" url:"description,omitempty"`
	Active          bool              `json:"active" url:"active"`
	AgentCode       *string           `json:"agentCode,omitempty" url:"agentCode,omitempty"`
	AgentAttributes []*AgentAttribute `json:"agentAttributes,omitempty" url:"agentAttributes,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *Agent) GetId() string {
	if a == nil {
		return ""
	}
	return a.Id
}

func (a *Agent) GetExternalId() *string {
	if a == nil {
		return nil
	}
	return a.ExternalId
}

func (a *Agent) GetOrganizationId() string {
	if a == nil {
		return ""
	}
	return a.OrganizationId
}

func (a *Agent) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *Agent) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *Agent) GetActive() bool {
	if a == nil {
		return false
	}
	return a.Active
}

func (a *Agent) GetAgentCode() *string {
	if a == nil {
		return nil
	}
	return a.AgentCode
}

func (a *Agent) GetAgentAttributes() []*AgentAttribute {
	if a == nil {
		return nil
	}
	return a.AgentAttributes
}

func (a *Agent) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *Agent) UnmarshalJSON(data []byte) error {
	type unmarshaler Agent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = Agent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *Agent) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AgentAttribute struct {
	Name    string   `json:"name" url:"name"`
	Active  bool     `json:"active" url:"active"`
	Pricing *Pricing `json:"pricing" url:"pricing"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentAttribute) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AgentAttribute) GetActive() bool {
	if a == nil {
		return false
	}
	return a.Active
}

func (a *AgentAttribute) GetPricing() *Pricing {
	if a == nil {
		return nil
	}
	return a.Pricing
}

func (a *AgentAttribute) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AgentAttribute) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentAttribute
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentAttribute(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentAttribute) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AgentPricePoint struct {
	UnitPrice        *float64                `json:"unitPrice,omitempty" url:"unitPrice,omitempty"`
	MinQuantity      *float64                `json:"minQuantity,omitempty" url:"minQuantity,omitempty"`
	IncludedQuantity *float64                `json:"includedQuantity,omitempty" url:"includedQuantity,omitempty"`
	Tiers            []*AgentPricePointTiers `json:"tiers,omitempty" url:"tiers,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentPricePoint) GetUnitPrice() *float64 {
	if a == nil {
		return nil
	}
	return a.UnitPrice
}

func (a *AgentPricePoint) GetMinQuantity() *float64 {
	if a == nil {
		return nil
	}
	return a.MinQuantity
}

func (a *AgentPricePoint) GetIncludedQuantity() *float64 {
	if a == nil {
		return nil
	}
	return a.IncludedQuantity
}

func (a *AgentPricePoint) GetTiers() []*AgentPricePointTiers {
	if a == nil {
		return nil
	}
	return a.Tiers
}

func (a *AgentPricePoint) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AgentPricePoint) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentPricePoint
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentPricePoint(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentPricePoint) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AgentPricePointTiers struct {
	MinQuantity *float64 `json:"minQuantity,omitempty" url:"minQuantity,omitempty"`
	MaxQuantity *float64 `json:"maxQuantity,omitempty" url:"maxQuantity,omitempty"`
	UnitPrice   float64  `json:"unitPrice" url:"unitPrice"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentPricePointTiers) GetMinQuantity() *float64 {
	if a == nil {
		return nil
	}
	return a.MinQuantity
}

func (a *AgentPricePointTiers) GetMaxQuantity() *float64 {
	if a == nil {
		return nil
	}
	return a.MaxQuantity
}

func (a *AgentPricePointTiers) GetUnitPrice() float64 {
	if a == nil {
		return 0
	}
	return a.UnitPrice
}

func (a *AgentPricePointTiers) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AgentPricePointTiers) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentPricePointTiers
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentPricePointTiers(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentPricePointTiers) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// An API error response from the Paid API
type ApiError struct {
	// A human-readable message providing more details about the error.
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	Code    *string `json:"code,omitempty" url:"code,omitempty"`
	Details *string `json:"details,omitempty" url:"details,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *ApiError) GetMessage() *string {
	if a == nil {
		return nil
	}
	return a.Message
}

func (a *ApiError) GetCode() *string {
	if a == nil {
		return nil
	}
	return a.Code
}

func (a *ApiError) GetDetails() *string {
	if a == nil {
		return nil
	}
	return a.Details
}

func (a *ApiError) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *ApiError) UnmarshalJSON(data []byte) error {
	type unmarshaler ApiError
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = ApiError(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *ApiError) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type BillingFrequency string

const (
	BillingFrequencyMonthly   BillingFrequency = "monthly"
	BillingFrequencyQuarterly BillingFrequency = "quarterly"
	BillingFrequencyAnnual    BillingFrequency = "annual"
)

func NewBillingFrequencyFromString(s string) (BillingFrequency, error) {
	switch s {
	case "monthly":
		return BillingFrequencyMonthly, nil
	case "quarterly":
		return BillingFrequencyQuarterly, nil
	case "annual":
		return BillingFrequencyAnnual, nil
	}
	var t BillingFrequency
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (b BillingFrequency) Ptr() *BillingFrequency {
	return &b
}

type ChargeType string

const (
	ChargeTypeOneTime   ChargeType = "oneTime"
	ChargeTypeRecurring ChargeType = "recurring"
	ChargeTypeUsage     ChargeType = "usage"
	ChargeTypeSeatBased ChargeType = "seatBased"
)

func NewChargeTypeFromString(s string) (ChargeType, error) {
	switch s {
	case "oneTime":
		return ChargeTypeOneTime, nil
	case "recurring":
		return ChargeTypeRecurring, nil
	case "usage":
		return ChargeTypeUsage, nil
	case "seatBased":
		return ChargeTypeSeatBased, nil
	}
	var t ChargeType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ChargeType) Ptr() *ChargeType {
	return &c
}

// Cost amount with currency
type CostAmount struct {
	// The cost amount
	Amount float64 `json:"amount" url:"amount"`
	// The currency code (e.g., "USD")
	Currency string `json:"currency" url:"currency"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CostAmount) GetAmount() float64 {
	if c == nil {
		return 0
	}
	return c.Amount
}

func (c *CostAmount) GetCurrency() string {
	if c == nil {
		return ""
	}
	return c.Currency
}

func (c *CostAmount) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CostAmount) UnmarshalJSON(data []byte) error {
	type unmarshaler CostAmount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CostAmount(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CostAmount) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreationSource string

const (
	CreationSourceManual CreationSource = "manual"
	CreationSourceApi    CreationSource = "api"
	CreationSourceCrm    CreationSource = "crm"
	CreationSourceOther  CreationSource = "other"
)

func NewCreationSourceFromString(s string) (CreationSource, error) {
	switch s {
	case "manual":
		return CreationSourceManual, nil
	case "api":
		return CreationSourceApi, nil
	case "crm":
		return CreationSourceCrm, nil
	case "other":
		return CreationSourceOther, nil
	}
	var t CreationSource
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreationSource) Ptr() *CreationSource {
	return &c
}

type CreationState string

const (
	CreationStateActive CreationState = "active"
	CreationStateDraft  CreationState = "draft"
)

func NewCreationStateFromString(s string) (CreationState, error) {
	switch s {
	case "active":
		return CreationStateActive, nil
	case "draft":
		return CreationStateDraft, nil
	}
	var t CreationState
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreationState) Ptr() *CreationState {
	return &c
}

type Customer struct {
	Id              string           `json:"id" url:"id"`
	OrganizationId  string           `json:"organizationId" url:"organizationId"`
	Name            string           `json:"name" url:"name"`
	ExternalId      *string          `json:"externalId,omitempty" url:"externalId,omitempty"`
	Phone           *string          `json:"phone,omitempty" url:"phone,omitempty"`
	EmployeeCount   *float64         `json:"employeeCount,omitempty" url:"employeeCount,omitempty"`
	AnnualRevenue   *float64         `json:"annualRevenue,omitempty" url:"annualRevenue,omitempty"`
	TaxExemptStatus *TaxExemptStatus `json:"taxExemptStatus,omitempty" url:"taxExemptStatus,omitempty"`
	CreationSource  *CreationSource  `json:"creationSource,omitempty" url:"creationSource,omitempty"`
	CreationState   *CreationState   `json:"creationState,omitempty" url:"creationState,omitempty"`
	Website         *string          `json:"website,omitempty" url:"website,omitempty"`
	BillingAddress  *Address         `json:"billingAddress,omitempty" url:"billingAddress,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *Customer) GetId() string {
	if c == nil {
		return ""
	}
	return c.Id
}

func (c *Customer) GetOrganizationId() string {
	if c == nil {
		return ""
	}
	return c.OrganizationId
}

func (c *Customer) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *Customer) GetExternalId() *string {
	if c == nil {
		return nil
	}
	return c.ExternalId
}

func (c *Customer) GetPhone() *string {
	if c == nil {
		return nil
	}
	return c.Phone
}

func (c *Customer) GetEmployeeCount() *float64 {
	if c == nil {
		return nil
	}
	return c.EmployeeCount
}

func (c *Customer) GetAnnualRevenue() *float64 {
	if c == nil {
		return nil
	}
	return c.AnnualRevenue
}

func (c *Customer) GetTaxExemptStatus() *TaxExemptStatus {
	if c == nil {
		return nil
	}
	return c.TaxExemptStatus
}

func (c *Customer) GetCreationSource() *CreationSource {
	if c == nil {
		return nil
	}
	return c.CreationSource
}

func (c *Customer) GetCreationState() *CreationState {
	if c == nil {
		return nil
	}
	return c.CreationState
}

func (c *Customer) GetWebsite() *string {
	if c == nil {
		return nil
	}
	return c.Website
}

func (c *Customer) GetBillingAddress() *Address {
	if c == nil {
		return nil
	}
	return c.BillingAddress
}

func (c *Customer) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *Customer) UnmarshalJSON(data []byte) error {
	type unmarshaler Customer
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = Customer(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *Customer) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// An error response from the Paid API
type Error struct {
	Error *ApiError `json:"error" url:"error"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *Error) GetError() *ApiError {
	if e == nil {
		return nil
	}
	return e.Error
}

func (e *Error) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *Error) UnmarshalJSON(data []byte) error {
	type unmarshaler Error
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = Error(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *Error) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type Order struct {
	Id                   *string        `json:"id,omitempty" url:"id,omitempty"`
	Name                 *string        `json:"name,omitempty" url:"name,omitempty"`
	Description          *string        `json:"description,omitempty" url:"description,omitempty"`
	CustomerId           *string        `json:"customerId,omitempty" url:"customerId,omitempty"`
	OrganizationId       *string        `json:"organizationId,omitempty" url:"organizationId,omitempty"`
	StartDate            *string        `json:"startDate,omitempty" url:"startDate,omitempty"`
	EndDate              *string        `json:"endDate,omitempty" url:"endDate,omitempty"`
	TotalAmount          *float64       `json:"totalAmount,omitempty" url:"totalAmount,omitempty"`
	EstimatedTax         *float64       `json:"estimatedTax,omitempty" url:"estimatedTax,omitempty"`
	BilledAmountNoTax    *float64       `json:"billedAmountNoTax,omitempty" url:"billedAmountNoTax,omitempty"`
	BilledTax            *float64       `json:"billedTax,omitempty" url:"billedTax,omitempty"`
	TotalBilledAmount    *float64       `json:"totalBilledAmount,omitempty" url:"totalBilledAmount,omitempty"`
	PendingBillingAmount *float64       `json:"pendingBillingAmount,omitempty" url:"pendingBillingAmount,omitempty"`
	CreationState        *CreationState `json:"creationState,omitempty" url:"creationState,omitempty"`
	OrderLines           []*OrderLine   `json:"orderLines,omitempty" url:"orderLines,omitempty"`
	Customer             *Customer      `json:"customer,omitempty" url:"customer,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *Order) GetId() *string {
	if o == nil {
		return nil
	}
	return o.Id
}

func (o *Order) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Order) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Order) GetCustomerId() *string {
	if o == nil {
		return nil
	}
	return o.CustomerId
}

func (o *Order) GetOrganizationId() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationId
}

func (o *Order) GetStartDate() *string {
	if o == nil {
		return nil
	}
	return o.StartDate
}

func (o *Order) GetEndDate() *string {
	if o == nil {
		return nil
	}
	return o.EndDate
}

func (o *Order) GetTotalAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.TotalAmount
}

func (o *Order) GetEstimatedTax() *float64 {
	if o == nil {
		return nil
	}
	return o.EstimatedTax
}

func (o *Order) GetBilledAmountNoTax() *float64 {
	if o == nil {
		return nil
	}
	return o.BilledAmountNoTax
}

func (o *Order) GetBilledTax() *float64 {
	if o == nil {
		return nil
	}
	return o.BilledTax
}

func (o *Order) GetTotalBilledAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.TotalBilledAmount
}

func (o *Order) GetPendingBillingAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.PendingBillingAmount
}

func (o *Order) GetCreationState() *CreationState {
	if o == nil {
		return nil
	}
	return o.CreationState
}

func (o *Order) GetOrderLines() []*OrderLine {
	if o == nil {
		return nil
	}
	return o.OrderLines
}

func (o *Order) GetCustomer() *Customer {
	if o == nil {
		return nil
	}
	return o.Customer
}

func (o *Order) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *Order) UnmarshalJSON(data []byte) error {
	type unmarshaler Order
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = Order(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *Order) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrderLine struct {
	Id                     *string               `json:"id,omitempty" url:"id,omitempty"`
	OrderId                *string               `json:"orderId,omitempty" url:"orderId,omitempty"`
	AgentId                *string               `json:"agentId,omitempty" url:"agentId,omitempty"`
	Name                   *string               `json:"name,omitempty" url:"name,omitempty"`
	Description            *string               `json:"description,omitempty" url:"description,omitempty"`
	StartDate              *string               `json:"startDate,omitempty" url:"startDate,omitempty"`
	EndDate                *string               `json:"endDate,omitempty" url:"endDate,omitempty"`
	TotalAmount            *float64              `json:"totalAmount,omitempty" url:"totalAmount,omitempty"`
	BilledAmountWithoutTax *float64              `json:"billedAmountWithoutTax,omitempty" url:"billedAmountWithoutTax,omitempty"`
	BilledTax              *float64              `json:"billedTax,omitempty" url:"billedTax,omitempty"`
	TotalBilledAmount      *float64              `json:"totalBilledAmount,omitempty" url:"totalBilledAmount,omitempty"`
	CreationState          *CreationState        `json:"creationState,omitempty" url:"creationState,omitempty"`
	Agent                  *Agent                `json:"agent,omitempty" url:"agent,omitempty"`
	OrderLineAttributes    []*OrderLineAttribute `json:"orderLineAttributes,omitempty" url:"orderLineAttributes,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrderLine) GetId() *string {
	if o == nil {
		return nil
	}
	return o.Id
}

func (o *OrderLine) GetOrderId() *string {
	if o == nil {
		return nil
	}
	return o.OrderId
}

func (o *OrderLine) GetAgentId() *string {
	if o == nil {
		return nil
	}
	return o.AgentId
}

func (o *OrderLine) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *OrderLine) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *OrderLine) GetStartDate() *string {
	if o == nil {
		return nil
	}
	return o.StartDate
}

func (o *OrderLine) GetEndDate() *string {
	if o == nil {
		return nil
	}
	return o.EndDate
}

func (o *OrderLine) GetTotalAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.TotalAmount
}

func (o *OrderLine) GetBilledAmountWithoutTax() *float64 {
	if o == nil {
		return nil
	}
	return o.BilledAmountWithoutTax
}

func (o *OrderLine) GetBilledTax() *float64 {
	if o == nil {
		return nil
	}
	return o.BilledTax
}

func (o *OrderLine) GetTotalBilledAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.TotalBilledAmount
}

func (o *OrderLine) GetCreationState() *CreationState {
	if o == nil {
		return nil
	}
	return o.CreationState
}

func (o *OrderLine) GetAgent() *Agent {
	if o == nil {
		return nil
	}
	return o.Agent
}

func (o *OrderLine) GetOrderLineAttributes() []*OrderLineAttribute {
	if o == nil {
		return nil
	}
	return o.OrderLineAttributes
}

func (o *OrderLine) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrderLine) UnmarshalJSON(data []byte) error {
	type unmarshaler OrderLine
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrderLine(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrderLine) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrderLineAttribute struct {
	AgentAttributeId *string                    `json:"agentAttributeId,omitempty" url:"agentAttributeId,omitempty"`
	Quantity         *float64                   `json:"quantity,omitempty" url:"quantity,omitempty"`
	Currency         *string                    `json:"currency,omitempty" url:"currency,omitempty"`
	Pricing          *OrderLineAttributePricing `json:"pricing,omitempty" url:"pricing,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrderLineAttribute) GetAgentAttributeId() *string {
	if o == nil {
		return nil
	}
	return o.AgentAttributeId
}

func (o *OrderLineAttribute) GetQuantity() *float64 {
	if o == nil {
		return nil
	}
	return o.Quantity
}

func (o *OrderLineAttribute) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *OrderLineAttribute) GetPricing() *OrderLineAttributePricing {
	if o == nil {
		return nil
	}
	return o.Pricing
}

func (o *OrderLineAttribute) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrderLineAttribute) UnmarshalJSON(data []byte) error {
	type unmarshaler OrderLineAttribute
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrderLineAttribute(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrderLineAttribute) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrderLineAttributeCreate struct {
	// The name of the agent attribute to override (e.g., "api_call", "call_placed")
	AgentAttributeName string `json:"agentAttributeName" url:"agentAttributeName"`
	// Quantity for this attribute (defaults to 0)
	Quantity *float64 `json:"quantity,omitempty" url:"quantity,omitempty"`
	// Custom pricing configuration for this attribute
	Pricing *OrderLineAttributePricing `json:"pricing" url:"pricing"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrderLineAttributeCreate) GetAgentAttributeName() string {
	if o == nil {
		return ""
	}
	return o.AgentAttributeName
}

func (o *OrderLineAttributeCreate) GetQuantity() *float64 {
	if o == nil {
		return nil
	}
	return o.Quantity
}

func (o *OrderLineAttributeCreate) GetPricing() *OrderLineAttributePricing {
	if o == nil {
		return nil
	}
	return o.Pricing
}

func (o *OrderLineAttributeCreate) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrderLineAttributeCreate) UnmarshalJSON(data []byte) error {
	type unmarshaler OrderLineAttributeCreate
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrderLineAttributeCreate(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrderLineAttributeCreate) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrderLineAttributePricing struct {
	EventName        *string           `json:"eventName,omitempty" url:"eventName,omitempty"`
	ChargeType       *ChargeType       `json:"chargeType,omitempty" url:"chargeType,omitempty"`
	PricePoint       *PricePoint       `json:"pricePoint,omitempty" url:"pricePoint,omitempty"`
	PricingModel     *PricingModelType `json:"pricingModel,omitempty" url:"pricingModel,omitempty"`
	BillingFrequency *BillingFrequency `json:"billingFrequency,omitempty" url:"billingFrequency,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrderLineAttributePricing) GetEventName() *string {
	if o == nil {
		return nil
	}
	return o.EventName
}

func (o *OrderLineAttributePricing) GetChargeType() *ChargeType {
	if o == nil {
		return nil
	}
	return o.ChargeType
}

func (o *OrderLineAttributePricing) GetPricePoint() *PricePoint {
	if o == nil {
		return nil
	}
	return o.PricePoint
}

func (o *OrderLineAttributePricing) GetPricingModel() *PricingModelType {
	if o == nil {
		return nil
	}
	return o.PricingModel
}

func (o *OrderLineAttributePricing) GetBillingFrequency() *BillingFrequency {
	if o == nil {
		return nil
	}
	return o.BillingFrequency
}

func (o *OrderLineAttributePricing) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrderLineAttributePricing) UnmarshalJSON(data []byte) error {
	type unmarshaler OrderLineAttributePricing
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrderLineAttributePricing(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrderLineAttributePricing) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrderLineCreate struct {
	// Paid's internal ID for the agent/product
	AgentId *string `json:"agentId,omitempty" url:"agentId,omitempty"`
	// The external ID of the agent/product i.e. the id within your system
	AgentExternalId *string `json:"agentExternalId,omitempty" url:"agentExternalId,omitempty"`
	// Name of the order line
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// Description of the order line
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Optional array of custom agent attributes to override default pricing, allowing per customer pricing. If not provided, attributes will be auto-generated from the product definition.
	AgentAttributes []*OrderLineAttributeCreate `json:"agentAttributes,omitempty" url:"agentAttributes,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrderLineCreate) GetAgentId() *string {
	if o == nil {
		return nil
	}
	return o.AgentId
}

func (o *OrderLineCreate) GetAgentExternalId() *string {
	if o == nil {
		return nil
	}
	return o.AgentExternalId
}

func (o *OrderLineCreate) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *OrderLineCreate) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *OrderLineCreate) GetAgentAttributes() []*OrderLineAttributeCreate {
	if o == nil {
		return nil
	}
	return o.AgentAttributes
}

func (o *OrderLineCreate) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrderLineCreate) UnmarshalJSON(data []byte) error {
	type unmarshaler OrderLineCreate
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrderLineCreate(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrderLineCreate) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

// Pagination metadata for cost traces
type PaginationMeta struct {
	// The requested limit
	Limit int `json:"limit" url:"limit"`
	// The requested offset
	Offset int `json:"offset" url:"offset"`
	// Number of items returned in this response
	Count int `json:"count" url:"count"`
	// Whether there are more results available
	HasMore bool `json:"hasMore" url:"hasMore"`
	// The startTime filter that was applied (if any)
	StartTime *time.Time `json:"startTime,omitempty" url:"startTime,omitempty"`
	// The endTime filter that was applied (if any)
	EndTime *time.Time `json:"endTime,omitempty" url:"endTime,omitempty"`
	// The externalCustomerId filter that was applied (if any)
	ExternalCustomerId *string `json:"externalCustomerId,omitempty" url:"externalCustomerId,omitempty"`
	// The externalAgentId filter that was applied (if any)
	ExternalAgentId *string `json:"externalAgentId,omitempty" url:"externalAgentId,omitempty"`
	// The metadata filter that was applied (if any)
	Metadata *string `json:"metadata,omitempty" url:"metadata,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaginationMeta) GetLimit() int {
	if p == nil {
		return 0
	}
	return p.Limit
}

func (p *PaginationMeta) GetOffset() int {
	if p == nil {
		return 0
	}
	return p.Offset
}

func (p *PaginationMeta) GetCount() int {
	if p == nil {
		return 0
	}
	return p.Count
}

func (p *PaginationMeta) GetHasMore() bool {
	if p == nil {
		return false
	}
	return p.HasMore
}

func (p *PaginationMeta) GetStartTime() *time.Time {
	if p == nil {
		return nil
	}
	return p.StartTime
}

func (p *PaginationMeta) GetEndTime() *time.Time {
	if p == nil {
		return nil
	}
	return p.EndTime
}

func (p *PaginationMeta) GetExternalCustomerId() *string {
	if p == nil {
		return nil
	}
	return p.ExternalCustomerId
}

func (p *PaginationMeta) GetExternalAgentId() *string {
	if p == nil {
		return nil
	}
	return p.ExternalAgentId
}

func (p *PaginationMeta) GetMetadata() *string {
	if p == nil {
		return nil
	}
	return p.Metadata
}

func (p *PaginationMeta) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PaginationMeta) UnmarshalJSON(data []byte) error {
	type embed PaginationMeta
	var unmarshaler = struct {
		embed
		StartTime *internal.DateTime `json:"startTime,omitempty"`
		EndTime   *internal.DateTime `json:"endTime,omitempty"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PaginationMeta(unmarshaler.embed)
	p.StartTime = unmarshaler.StartTime.TimePtr()
	p.EndTime = unmarshaler.EndTime.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginationMeta) MarshalJSON() ([]byte, error) {
	type embed PaginationMeta
	var marshaler = struct {
		embed
		StartTime *internal.DateTime `json:"startTime,omitempty"`
		EndTime   *internal.DateTime `json:"endTime,omitempty"`
	}{
		embed:     embed(*p),
		StartTime: internal.NewOptionalDateTime(p.StartTime),
		EndTime:   internal.NewOptionalDateTime(p.EndTime),
	}
	return json.Marshal(marshaler)
}

func (p *PaginationMeta) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PricePoint struct {
	Currency    *string  `json:"currency,omitempty" url:"currency,omitempty"`
	UnitPrice   *float64 `json:"unitPrice,omitempty" url:"unitPrice,omitempty"`
	MinQuantity *float64 `json:"minQuantity,omitempty" url:"minQuantity,omitempty"`
	Tiers       []*Tier  `json:"tiers,omitempty" url:"tiers,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PricePoint) GetCurrency() *string {
	if p == nil {
		return nil
	}
	return p.Currency
}

func (p *PricePoint) GetUnitPrice() *float64 {
	if p == nil {
		return nil
	}
	return p.UnitPrice
}

func (p *PricePoint) GetMinQuantity() *float64 {
	if p == nil {
		return nil
	}
	return p.MinQuantity
}

func (p *PricePoint) GetTiers() []*Tier {
	if p == nil {
		return nil
	}
	return p.Tiers
}

func (p *PricePoint) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PricePoint) UnmarshalJSON(data []byte) error {
	type unmarshaler PricePoint
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PricePoint(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PricePoint) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type Pricing struct {
	EventName        *string                     `json:"eventName,omitempty" url:"eventName,omitempty"`
	Taxable          bool                        `json:"taxable" url:"taxable"`
	CreditCost       *float64                    `json:"creditCost,omitempty" url:"creditCost,omitempty"`
	ChargeType       ChargeType                  `json:"chargeType" url:"chargeType"`
	PricingModel     PricingModelType            `json:"pricingModel" url:"pricingModel"`
	BillingFrequency BillingFrequency            `json:"billingFrequency" url:"billingFrequency"`
	PricePoints      map[string]*AgentPricePoint `json:"pricePoints" url:"pricePoints"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *Pricing) GetEventName() *string {
	if p == nil {
		return nil
	}
	return p.EventName
}

func (p *Pricing) GetTaxable() bool {
	if p == nil {
		return false
	}
	return p.Taxable
}

func (p *Pricing) GetCreditCost() *float64 {
	if p == nil {
		return nil
	}
	return p.CreditCost
}

func (p *Pricing) GetChargeType() ChargeType {
	if p == nil {
		return ""
	}
	return p.ChargeType
}

func (p *Pricing) GetPricingModel() PricingModelType {
	if p == nil {
		return ""
	}
	return p.PricingModel
}

func (p *Pricing) GetBillingFrequency() BillingFrequency {
	if p == nil {
		return ""
	}
	return p.BillingFrequency
}

func (p *Pricing) GetPricePoints() map[string]*AgentPricePoint {
	if p == nil {
		return nil
	}
	return p.PricePoints
}

func (p *Pricing) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *Pricing) UnmarshalJSON(data []byte) error {
	type unmarshaler Pricing
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = Pricing(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *Pricing) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PricingModelType string

const (
	PricingModelTypePerUnit          PricingModelType = "PerUnit"
	PricingModelTypeVolumePricing    PricingModelType = "VolumePricing"
	PricingModelTypeGraduatedPricing PricingModelType = "GraduatedPricing"
	PricingModelTypePrepaidCredits   PricingModelType = "PrepaidCredits"
)

func NewPricingModelTypeFromString(s string) (PricingModelType, error) {
	switch s {
	case "PerUnit":
		return PricingModelTypePerUnit, nil
	case "VolumePricing":
		return PricingModelTypeVolumePricing, nil
	case "GraduatedPricing":
		return PricingModelTypeGraduatedPricing, nil
	case "PrepaidCredits":
		return PricingModelTypePrepaidCredits, nil
	}
	var t PricingModelType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PricingModelType) Ptr() *PricingModelType {
	return &p
}

type TaxExemptStatus string

const (
	TaxExemptStatusNone    TaxExemptStatus = "none"
	TaxExemptStatusExempt  TaxExemptStatus = "exempt"
	TaxExemptStatusReverse TaxExemptStatus = "reverse"
)

func NewTaxExemptStatusFromString(s string) (TaxExemptStatus, error) {
	switch s {
	case "none":
		return TaxExemptStatusNone, nil
	case "exempt":
		return TaxExemptStatusExempt, nil
	case "reverse":
		return TaxExemptStatusReverse, nil
	}
	var t TaxExemptStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TaxExemptStatus) Ptr() *TaxExemptStatus {
	return &t
}

type Tier struct {
	LowerBound *float64 `json:"lowerBound,omitempty" url:"lowerBound,omitempty"`
	UpperBound *float64 `json:"upperBound,omitempty" url:"upperBound,omitempty"`
	Price      *float64 `json:"price,omitempty" url:"price,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *Tier) GetLowerBound() *float64 {
	if t == nil {
		return nil
	}
	return t.LowerBound
}

func (t *Tier) GetUpperBound() *float64 {
	if t == nil {
		return nil
	}
	return t.UpperBound
}

func (t *Tier) GetPrice() *float64 {
	if t == nil {
		return nil
	}
	return t.Price
}

func (t *Tier) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *Tier) UnmarshalJSON(data []byte) error {
	type unmarshaler Tier
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = Tier(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *Tier) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
