// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "sdk/internal"
)

type UsageRecordBulkRequest struct {
	Signals []*Signal `json:"signals,omitempty" url:"-"`
}

type Signal struct {
	EventName       *string `json:"event_name,omitempty" url:"event_name,omitempty"`
	AgentId         *string `json:"agent_id,omitempty" url:"agent_id,omitempty"`
	ExternalAgentId *string `json:"external_agent_id,omitempty" url:"external_agent_id,omitempty"`
	// Deprecated. The external customer id. Use `external_customer_id` or `internal_customer_id` instead.
	CustomerId *string                `json:"customer_id,omitempty" url:"customer_id,omitempty"`
	Data       map[string]interface{} `json:"data,omitempty" url:"data,omitempty"`
	// A unique key to ensure idempotent signal processing
	IdempotencyKey *string `json:"idempotency_key,omitempty" url:"idempotency_key,omitempty"`
	// Paid's internal customer ID
	InternalCustomerId *string `json:"internal_customer_id,omitempty" url:"internal_customer_id,omitempty"`
	// Your system's customer ID
	ExternalCustomerId *string `json:"external_customer_id,omitempty" url:"external_customer_id,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *Signal) GetEventName() *string {
	if s == nil {
		return nil
	}
	return s.EventName
}

func (s *Signal) GetAgentId() *string {
	if s == nil {
		return nil
	}
	return s.AgentId
}

func (s *Signal) GetExternalAgentId() *string {
	if s == nil {
		return nil
	}
	return s.ExternalAgentId
}

func (s *Signal) GetCustomerId() *string {
	if s == nil {
		return nil
	}
	return s.CustomerId
}

func (s *Signal) GetData() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *Signal) GetIdempotencyKey() *string {
	if s == nil {
		return nil
	}
	return s.IdempotencyKey
}

func (s *Signal) GetInternalCustomerId() *string {
	if s == nil {
		return nil
	}
	return s.InternalCustomerId
}

func (s *Signal) GetExternalCustomerId() *string {
	if s == nil {
		return nil
	}
	return s.ExternalCustomerId
}

func (s *Signal) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *Signal) UnmarshalJSON(data []byte) error {
	type unmarshaler Signal
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = Signal(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *Signal) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
