// Code generated by Fern. DO NOT EDIT.

package plans

import (
	context "context"
	paidgo "github.com/paid-ai/paid-go"
	core "github.com/paid-ai/paid-go/core"
	internal "github.com/paid-ai/paid-go/internal"
	option "github.com/paid-ai/paid-go/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Returns plans for your organization, including archived plans by default, optionally filtered to a product.
func (c *Client) ListPlans(
	ctx context.Context,
	request *paidgo.ListPlansRequest,
	opts ...option.RequestOption,
) (*paidgo.PlanListResponse, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.agentpaid.io/api/v2",
	)
	endpointURL := baseURL + "/plans/"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	errorCodes := internal.ErrorCodes{
		400: func(apiError *core.APIError) error {
			return &paidgo.BadRequestError{
				APIError: apiError,
			}
		},
		403: func(apiError *core.APIError) error {
			return &paidgo.ForbiddenError{
				APIError: apiError,
			}
		},
		404: func(apiError *core.APIError) error {
			return &paidgo.NotFoundError{
				APIError: apiError,
			}
		},
		500: func(apiError *core.APIError) error {
			return &paidgo.InternalServerError{
				APIError: apiError,
			}
		},
	}

	var response *paidgo.PlanListResponse
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Creates a new plan for a product.
func (c *Client) CreatePlan(
	ctx context.Context,
	request *paidgo.CreatePlanRequest,
	opts ...option.RequestOption,
) (*paidgo.Plan, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.agentpaid.io/api/v2",
	)
	endpointURL := baseURL + "/plans/"
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	headers.Set("Content-Type", "application/json")
	errorCodes := internal.ErrorCodes{
		400: func(apiError *core.APIError) error {
			return &paidgo.BadRequestError{
				APIError: apiError,
			}
		},
		403: func(apiError *core.APIError) error {
			return &paidgo.ForbiddenError{
				APIError: apiError,
			}
		},
		404: func(apiError *core.APIError) error {
			return &paidgo.NotFoundError{
				APIError: apiError,
			}
		},
		500: func(apiError *core.APIError) error {
			return &paidgo.InternalServerError{
				APIError: apiError,
			}
		},
	}

	var response *paidgo.Plan
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Updates upgrade path ordering for plans within a product, grouped by billing frequency.
func (c *Client) UpdatePlanUpgradePath(
	ctx context.Context,
	request *paidgo.UpdatePlanUpgradePathRequest,
	opts ...option.RequestOption,
) (*paidgo.PlanUpgradePathResponse, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.agentpaid.io/api/v2",
	)
	endpointURL := baseURL + "/plans/upgrade-path"
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	headers.Set("Content-Type", "application/json")
	errorCodes := internal.ErrorCodes{
		400: func(apiError *core.APIError) error {
			return &paidgo.BadRequestError{
				APIError: apiError,
			}
		},
		403: func(apiError *core.APIError) error {
			return &paidgo.ForbiddenError{
				APIError: apiError,
			}
		},
		404: func(apiError *core.APIError) error {
			return &paidgo.NotFoundError{
				APIError: apiError,
			}
		},
		500: func(apiError *core.APIError) error {
			return &paidgo.InternalServerError{
				APIError: apiError,
			}
		},
	}

	var response *paidgo.PlanUpgradePathResponse
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Get a plan by Paid plan ID.
func (c *Client) GetPlanByID(
	ctx context.Context,
	request *paidgo.GetPlanByIDRequest,
	opts ...option.RequestOption,
) (*paidgo.Plan, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.agentpaid.io/api/v2",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/plans/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	errorCodes := internal.ErrorCodes{
		403: func(apiError *core.APIError) error {
			return &paidgo.ForbiddenError{
				APIError: apiError,
			}
		},
		404: func(apiError *core.APIError) error {
			return &paidgo.NotFoundError{
				APIError: apiError,
			}
		},
		500: func(apiError *core.APIError) error {
			return &paidgo.InternalServerError{
				APIError: apiError,
			}
		},
	}

	var response *paidgo.Plan
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Update a plan by Paid plan ID. If attributes are provided, they replace the plan's existing attributes. Set status to archive or restore the plan.
func (c *Client) UpdatePlanByID(
	ctx context.Context,
	request *paidgo.UpdatePlanByIDRequest,
	opts ...option.RequestOption,
) (*paidgo.Plan, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.agentpaid.io/api/v2",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/plans/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	headers.Set("Content-Type", "application/json")
	errorCodes := internal.ErrorCodes{
		400: func(apiError *core.APIError) error {
			return &paidgo.BadRequestError{
				APIError: apiError,
			}
		},
		403: func(apiError *core.APIError) error {
			return &paidgo.ForbiddenError{
				APIError: apiError,
			}
		},
		404: func(apiError *core.APIError) error {
			return &paidgo.NotFoundError{
				APIError: apiError,
			}
		},
		500: func(apiError *core.APIError) error {
			return &paidgo.InternalServerError{
				APIError: apiError,
			}
		},
	}

	var response *paidgo.Plan
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Get a plan by your external plan ID.
func (c *Client) GetPlanByExternalID(
	ctx context.Context,
	request *paidgo.GetPlanByExternalIDRequest,
	opts ...option.RequestOption,
) (*paidgo.Plan, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.agentpaid.io/api/v2",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/plans/external/%v",
		request.ExternalID,
	)
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	errorCodes := internal.ErrorCodes{
		403: func(apiError *core.APIError) error {
			return &paidgo.ForbiddenError{
				APIError: apiError,
			}
		},
		404: func(apiError *core.APIError) error {
			return &paidgo.NotFoundError{
				APIError: apiError,
			}
		},
		500: func(apiError *core.APIError) error {
			return &paidgo.InternalServerError{
				APIError: apiError,
			}
		},
	}

	var response *paidgo.Plan
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Update a plan by your external plan ID. If attributes are provided, they replace the plan's existing attributes. Set status to archive or restore the plan.
func (c *Client) UpdatePlanByExternalID(
	ctx context.Context,
	request *paidgo.UpdatePlanByExternalIDRequest,
	opts ...option.RequestOption,
) (*paidgo.Plan, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.agentpaid.io/api/v2",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/plans/external/%v",
		request.ExternalID,
	)
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	headers.Set("Content-Type", "application/json")
	errorCodes := internal.ErrorCodes{
		400: func(apiError *core.APIError) error {
			return &paidgo.BadRequestError{
				APIError: apiError,
			}
		},
		403: func(apiError *core.APIError) error {
			return &paidgo.ForbiddenError{
				APIError: apiError,
			}
		},
		404: func(apiError *core.APIError) error {
			return &paidgo.NotFoundError{
				APIError: apiError,
			}
		},
		500: func(apiError *core.APIError) error {
			return &paidgo.InternalServerError{
				APIError: apiError,
			}
		},
	}

	var response *paidgo.Plan
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
