// Code generated by Fern. DO NOT EDIT.

package credits

import (
	context "context"
	paidgo "github.com/paid-ai/paid-go"
	core "github.com/paid-ai/paid-go/core"
	internal "github.com/paid-ai/paid-go/internal"
	option "github.com/paid-ai/paid-go/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// List credit currencies for the organization
func (c *Client) ListCreditCurrencies(
	ctx context.Context,
	opts ...option.RequestOption,
) (*paidgo.CreditCurrencyListResponse, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://api.agentpaid.io/api/v2",
	)
	endpointURL := baseURL + "/credits/currencies"
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	errorCodes := internal.ErrorCodes{
		403: func(apiError *core.APIError) error {
			return &paidgo.ForbiddenError{
				APIError: apiError,
			}
		},
		500: func(apiError *core.APIError) error {
			return &paidgo.InternalServerError{
				APIError: apiError,
			}
		},
	}

	var response *paidgo.CreditCurrencyListResponse
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
